SELECT
	*
FROM
	TbEntidade(NOLOCK) e
WHERE
UPPER(e.Texto) like '%NOME DO FILIADO%' OR 
UPPER(e.Texto) like '%RAIMUNDO VAZ DE ABREU%' OR 
UPPER(e.Texto) like '%PAULO CORREA FEITOZA%' OR 
UPPER(e.Texto) like '%FRANCISCA ODETE PONCIANO DE SOUSA%' OR 
UPPER(e.Texto) like '%EVANEIDE DA SILVA MENDES%' OR 
UPPER(e.Texto) like '%MILTON DE LIMA FURTADO%' OR 
UPPER(e.Texto) like '%IVANILDE MENDES DE SOUZA%' OR 
UPPER(e.Texto) like '%MARILENE FELIPE DA SILVA%' OR 
UPPER(e.Texto) like '%KARIL SHESMA NASCIMENTO DE SOUZA%' OR 
UPPER(e.Texto) like '%ELIZABETH GONZAGA DO VALE%' OR 
UPPER(e.Texto) like '%IVANEIDE ALVES BATISTA%' OR 
UPPER(e.Texto) like '%FRANCISCO FERREIRA PISCO%' OR 
UPPER(e.Texto) like '%MARIA NUNES DE ALMEIDA%' OR 
UPPER(e.Texto) like '%MARLENE FERNANDES OLIVEIRA%' OR 
UPPER(e.Texto) like '%FERNANDO OLIVEIRA DA CUNHA%' OR 
UPPER(e.Texto) like '%JOSIMAR BRANDO DA COSTA%' OR 
UPPER(e.Texto) like '%ADAILTON FERNANDES MODESTO%' OR 
UPPER(e.Texto) like '%PAULO SERGIO DO NASCIMENTO SILVA%' OR 
UPPER(e.Texto) like '%CLAUDEMIR DA COSTA SOUZA%' OR 
UPPER(e.Texto) like '%CLAUDEMIR DA COSTA SOUZA%' OR 
UPPER(e.Texto) like '%JOSE MARIA OLIVEIRA DE SOUZA%' OR 
UPPER(e.Texto) like '%ADOLFO WANDERLEI DE ARAUJO PERDOME%' OR 
UPPER(e.Texto) like '%ANTONIO NONATO DA SILVA%' OR 
UPPER(e.Texto) like '%ANTONIO PEREIRA DE ARAUJO%' OR 
UPPER(e.Texto) like '%MARIA DO SOCORRO DA SILVA BEZERRA%' OR 
UPPER(e.Texto) like '%FRANCISCA PINTO DE ARAUJO%' OR 
UPPER(e.Texto) like '%MARIA DA CONCEICAO NASCIMENTO%' OR 
UPPER(e.Texto) like '%MARIA DA CONCEICAO NASCIMENTO%' OR 
UPPER(e.Texto) like '%FRANCISCA ALDALEIA SANTOS DA SILVA%' OR 
UPPER(e.Texto) like '%FRANCISCA ALDALEIA SANTOS DA SILVA%' OR 
UPPER(e.Texto) like '%AMADEUS GOMES DA SILVA%' OR 
UPPER(e.Texto) like '%CLAVIS LEONTINO DA SILVA%' OR 
UPPER(e.Texto) like '%ABDIAS DA SILVA MATOS%' OR 
UPPER(e.Texto) like '%DEYWD DE LIMA ARAUJO%' OR 
UPPER(e.Texto) like '%CELINA DO ESPIRITO SANTO DE SOUZA%' OR 
UPPER(e.Texto) like '%ALTEVIR RODRIGUES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%SEBASTIAO VIEIRA DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%JOAO FERREIRA DE ANDRADE%' OR 
UPPER(e.Texto) like '%ANTONIO JOSE OLIMPIO DA SILVA%' OR 
UPPER(e.Texto) like '%ANTONIO JOSE OLIMPIO DA SILVA%' OR 
UPPER(e.Texto) like '%SETEMBRINO FERNANDES DE CARVALHO FILHO%' OR 
UPPER(e.Texto) like '%MARLY LIMA AGUIAR%' OR 
UPPER(e.Texto) like '%JOSE RAIMUNDO SOUZA DA SILVA%' OR 
UPPER(e.Texto) like '%ERASMO DA COSTA SILVA%' OR 
UPPER(e.Texto) like '%FRANCISCO JOSE DA CRUZ%' OR 
UPPER(e.Texto) like '%EDINA CUNHA MAGALHAES%' OR 
UPPER(e.Texto) like '%ELINEY MOREIRA PEREIRA%' OR 
UPPER(e.Texto) like '%ELIAS GOMES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%FRANCINETE ANDRADE DE ARAGAO%' OR 
UPPER(e.Texto) like '%JOSE AFONCO TEIXEIRA%' OR 
UPPER(e.Texto) like '%ANTONIO LEOMAR BATISTA DE SOUZA%' OR 
UPPER(e.Texto) like '%OSWALDO DE CARVALHO COELHO%' OR 
UPPER(e.Texto) like '%MARIA DA CONCEICAO MARTINS DE ALMEIDA%' OR 
UPPER(e.Texto) like '%MARIA MADALENA DOS SANTOS OLIVEIRA%' OR 
UPPER(e.Texto) like '%MARIA MADALENA DOS SANTOS OLIVEIRA%' OR 
UPPER(e.Texto) like '%MARIA NAZARE DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%IDELCLEIDE RODRIGUES LIMA%' OR 
UPPER(e.Texto) like '%LUCINEIDE DA SILVA NASCIMENTO%' OR 
UPPER(e.Texto) like '%MANOEL JAIME VIANA%' OR 
UPPER(e.Texto) like '%RAIMUNDO NASCIMENTO RODRIGUES%' OR 
UPPER(e.Texto) like '%EUNICE ANDRADE PEREIRA%' OR 
UPPER(e.Texto) like '%SANDRA MARIA MATOS MARINHO%' OR 
UPPER(e.Texto) like '%AUCIMAR VASCONCELOS PINHEIRO%' OR 
UPPER(e.Texto) like '%ESMAEL SANTOS DA SILVA%' OR 
UPPER(e.Texto) like '%ANTONIA NASCIMENTO DE SOUZA%' OR 
UPPER(e.Texto) like '%MARIA LUCIA SZUTA%' OR 
UPPER(e.Texto) like '%MARIA LUCIA SZUTA%' OR 
UPPER(e.Texto) like '%RAIMUNDO MENEZES DA SILVA%' OR 
UPPER(e.Texto) like '%JOSE ROSSINEY GOMES RODRIGUES%' OR 
UPPER(e.Texto) like '%JONES ROBERTO REGO DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA DAS GRACAS QUEIROZ DOS ANJOS DA SILVA%' OR 
UPPER(e.Texto) like '%NILDA DANTAS PIRES%' OR 
UPPER(e.Texto) like '%SILVIA PERET CANIZO%' OR 
UPPER(e.Texto) like '%FRANCISCA DA ROCHA%' OR 
UPPER(e.Texto) like '%WANDERLEI NOLASCO NERYS%' OR 
UPPER(e.Texto) like '%SILAS SENHORINHA DE ALENCAR%' OR 
UPPER(e.Texto) like '%ROBERTO PAIVA DE SOUZA%' OR 
UPPER(e.Texto) like '%GENILDO ASSUNCAO DA CONCEICAO%' OR 
UPPER(e.Texto) like '%ROSA MARIA RODRIGUES DE ARAUJO%' OR 
UPPER(e.Texto) like '%ROGERIO DE JESUS CANIZO%' OR 
UPPER(e.Texto) like '%MARIA LUIZA FREIRE DA CONCEICAO%' OR 
UPPER(e.Texto) like '%ADELSON DA SILVA%' OR 
UPPER(e.Texto) like '%ANTONIA SUELY SILVA DE ALMEIDA%' OR 
UPPER(e.Texto) like '%ANTONIA SUELY SILVA DE ALMEIDA%' OR 
UPPER(e.Texto) like '%WALDEMAR MARQUES DE SOUZA%' OR 
UPPER(e.Texto) like '%REGIANE CABRAL DA SILVA%' OR 
UPPER(e.Texto) like '%DALETE MOREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%DALETE MOREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%MANOEL FRANCISCO GOMES ARARA%' OR 
UPPER(e.Texto) like '%ARY PAIVA DE ALMEIDA%' OR 
UPPER(e.Texto) like '%JOSE DELFINO MIRAO GONCALVES%' OR 
UPPER(e.Texto) like '%MARIA DO CARMO RODRIGUES DE ALMEIDA%' OR 
UPPER(e.Texto) like '%NAZARE LIMA DE SOUZA%' OR 
UPPER(e.Texto) like '%MARIA FERREIRA PISCO%' OR 
UPPER(e.Texto) like '%REGIS QUEVEDO NOGUEIRA%' OR 
UPPER(e.Texto) like '%FRANCISCA DE OLIVEIRA RIOS%' OR 
UPPER(e.Texto) like '%FRANCINEIDE DOMINGOS%' OR 
UPPER(e.Texto) like '%RAIMUNDO GUSTAVO ALMEIDA DE CARVALHO%' OR 
UPPER(e.Texto) like '%ROSA MARIA DOS ANJOS CHAVES%' OR 
UPPER(e.Texto) like '%FRANCISCO IZIDIO DE MOURA%' OR 
UPPER(e.Texto) like '%INALVA GERALDO DA SILVA%' OR 
UPPER(e.Texto) like '%INALVA GERALDO DA SILVA%' OR 
UPPER(e.Texto) like '%ODAIR JOSE DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA MARLICE BARBOSA MOTA%' OR 
UPPER(e.Texto) like '%ROBSON MARTINS DE SOUZA%' OR 
UPPER(e.Texto) like '%ROSANIRA SOARES LIMA%' OR 
UPPER(e.Texto) like '%MARIA DE FATIMA LIMA DIAS%' OR 
UPPER(e.Texto) like '%MAURICIO FERREIRA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%OCIMAR SOARES DE QUEIROZ%' OR 
UPPER(e.Texto) like '%AYRTON GEBER%' OR 
UPPER(e.Texto) like '%RAIMUNDO NONATO DE OLIVEIRA LIMA%' OR 
UPPER(e.Texto) like '%VERIDIANO FRANCISCO OLIVEIRA DA CUNHA%' OR 
UPPER(e.Texto) like '%VERIDIANO FRANCISCO OLIVEIRA DA CUNHA%' OR 
UPPER(e.Texto) like '%MARIA CANDIDA DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%MARIA CANDIDA DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%GILMAR SILVEIRA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%PEDRO SIMAO LIMA DE SOUSA%' OR 
UPPER(e.Texto) like '%ROSA MARIA BATALHA SALES%' OR 
UPPER(e.Texto) like '%MARIA DE FATIMA DA SILVA LIRA%' OR 
UPPER(e.Texto) like '%MARIA DE FATIMA DA SILVA LIRA%' OR 
UPPER(e.Texto) like '%RENATO PEREIRA DE CASTRO%' OR 
UPPER(e.Texto) like '%SEBASTIANA ALVES DE SOUZA%' OR 
UPPER(e.Texto) like '%SEBASTIANA ALVES DE SOUZA%' OR 
UPPER(e.Texto) like '%CASSIA ANGELICA LIMA DE CARVALHO%' OR 
UPPER(e.Texto) like '%FRANCISCA DE JESUS DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%FRANCISCA DE JESUS DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%MARIA MARLENNILZA MARINHO DE FARIAS%' OR 
UPPER(e.Texto) like '%FRANCISCO GOMES PONTES%' OR 
UPPER(e.Texto) like '%CESAR GOMES DE LIMA%' OR 
UPPER(e.Texto) like '%CESAR GOMES DE LIMA%' OR 
UPPER(e.Texto) like '%OSCAR XAVIER DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%JOAO ANTONIO MENDES DA SILVA%' OR 
UPPER(e.Texto) like '%RAIMUNDO RIBEIRO DE SOUZA%' OR 
UPPER(e.Texto) like '%SONIA MARIA BARBOSA DE SOUZA%' OR 
UPPER(e.Texto) like '%SONIA MARIA BARBOSA DE SOUZA%' OR 
UPPER(e.Texto) like '%MARIA CONCEICAO DE OLIVEIRA MAIA%' OR 
UPPER(e.Texto) like '%CARLOS ALBERTO DA SILVA MATIAS%' OR 
UPPER(e.Texto) like '%ELIAS FERREIRA DE ANDRADE%' OR 
UPPER(e.Texto) like '%MAURO AFONSO DIAS MARQUES%' OR 
UPPER(e.Texto) like '%MAURO AFONSO DIAS MARQUES%' OR 
UPPER(e.Texto) like '%MARIA MARLUCE PEPES GOMES%' OR 
UPPER(e.Texto) like '%FRANCILENE RIBEIRO DA SILVA%' OR 
UPPER(e.Texto) like '%PAULO SILVIO ZUZA DA COSTA%' OR 
UPPER(e.Texto) like '%ROSIENE COSTA DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA CIRLANDIA CAVALCANTE DA CONCEICAO%' OR 
UPPER(e.Texto) like '%MARINEZ ALFONCO DA SILVA%' OR 
UPPER(e.Texto) like '%ROBERTO CARLOS ALVES NASSERALA%' OR 
UPPER(e.Texto) like '%FRANCISCO DE ARAUJO NASCIMENTO%' OR 
UPPER(e.Texto) like '%ADELCIDE SANTANA DE RIBEIRO%' OR 
UPPER(e.Texto) like '%EDICIULA MELO DOS SANTOS%' OR 
UPPER(e.Texto) like '%JOSE SOARES DA SILVA%' OR 
UPPER(e.Texto) like '%ALCENIRA EMIDIO DA SILVA DE SOUZA%' OR 
UPPER(e.Texto) like '%MARIA JOVE GOMES DA ROCHA%' OR 
UPPER(e.Texto) like '%FRANCISCO MARTINS DE LIMA%' OR 
UPPER(e.Texto) like '%FRANCISCO MARTINS DE LIMA%' OR 
UPPER(e.Texto) like '%FRANCISCO DE ASSIS FARIAS DA SILVA JUNIOR%' OR 
UPPER(e.Texto) like '%MARIA DAS GRACAS BRAGA DE HOLANDA%' OR 
UPPER(e.Texto) like '%SEBASTIAO GADELHA DE MENEZES%' OR 
UPPER(e.Texto) like '%ANGELA MARIA NUNES DA COSTA%' OR 
UPPER(e.Texto) like '%ODAISA DA SILVA CABRAL%' OR 
UPPER(e.Texto) like '%JOSE FRANCISCO BRAGA DE PAULA%' OR 
UPPER(e.Texto) like '%MARIA SOCORRO DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA SOCORRO DA SILVA%' OR 
UPPER(e.Texto) like '%ADEMAR SOUSA ROCHA JUNIOR%' OR 
UPPER(e.Texto) like '%MARIA SALETE DE OLIVEIRA MAIA%' OR 
UPPER(e.Texto) like '%LUCI DE ALMEIDA LIMA%' OR 
UPPER(e.Texto) like '%MARIA SILVIA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%IZAIAS JORGE DOS SANTOS MATOS%' OR 
UPPER(e.Texto) like '%MARIA OSVANILDA DO SACRAMENTO MARTINS%' OR 
UPPER(e.Texto) like '%MARCOS ROBERTO DO NASCIMENTO CHAGAS%' OR 
UPPER(e.Texto) like '%MARCOS ARINO DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%MARCOS ARINO DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%RAIMUNDO LOPES DA SILVA%' OR 
UPPER(e.Texto) like '%RAIMUNDO LOPES DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA DA SILVA DE ARRUDA%' OR 
UPPER(e.Texto) like '%MARIA DA SILVA DE ARRUDA%' OR 
UPPER(e.Texto) like '%ALDEMIR PEREIRA GUERRA%' OR 
UPPER(e.Texto) like '%SANDRA MARIA MOREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA ANTONIA DOS SANTOS SILVA%' OR 
UPPER(e.Texto) like '%JOSE MEZERHANE ACACIO%' OR 
UPPER(e.Texto) like '%ANTONIO SANTANA MATOS%' OR 
UPPER(e.Texto) like '%CLAUDETE DE PAIVA BEZERRA%' OR 
UPPER(e.Texto) like '%MARIA DO CARMO ARAUJO BRITO%' OR 
UPPER(e.Texto) like '%ANA LUCIA MAIA JANSEN%' OR 
UPPER(e.Texto) like '%ANA LUCIA MAIA JANSEN%' OR 
UPPER(e.Texto) like '%JOSIAS BARBOSA DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%BRIGIDA DARIA DE ALMEIDA SANTOS%' OR 
UPPER(e.Texto) like '%FRANCISCO CIPRIANO DA SILVA%' OR 
UPPER(e.Texto) like '%RIVALDO DOS SANTOS BARROS%' OR 
UPPER(e.Texto) like '%RITA MARIA DE FREITAS MELO%' OR 
UPPER(e.Texto) like '%ROBERTO PAULO SILVA DE ALMEIDA%' OR 
UPPER(e.Texto) like '%GILBERTO GIL GOUVEIA DINIZ%' OR 
UPPER(e.Texto) like '%MARIA DE FATIMA PAIVA DE SOUZA%' OR 
UPPER(e.Texto) like '%GERCINEIDE BARROZO DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%GERCINEIDE BARROZO DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%CLAUDIO ROBERTO BERNARDO DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%CORDELIA BRAZ DA FONSECA%' OR 
UPPER(e.Texto) like '%WELLINGTON BRANDO DE MELO%' OR 
UPPER(e.Texto) like '%NECIA LOPES CUNHA%' OR 
UPPER(e.Texto) like '%NECIA LOPES CUNHA%' OR 
UPPER(e.Texto) like '%DAISY DE FATIMA BRASIL COSTA%' OR 
UPPER(e.Texto) like '%FRANCISCO JOSE CRISPIM DE SOUZA%' OR 
UPPER(e.Texto) like '%FRANCISCO JOSE CRISPIM DE SOUZA%' OR 
UPPER(e.Texto) like '%MARIA DE FATIMA SILVA MARTINS%' OR 
UPPER(e.Texto) like '%FATIMA MARIA ALVES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%FATIMA MARIA ALVES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%OTAVIO BARBOSA DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%JOSE PEREIRA SOARES%' OR 
UPPER(e.Texto) like '%PEREGRINA GOMES ELEUTERIO%' OR 
UPPER(e.Texto) like '%MARINES GOMES DA SILVA%' OR 
UPPER(e.Texto) like '%JOSE ALERCI DOS SANTOS MELO%' OR 
UPPER(e.Texto) like '%MARCONDES DE SOUZA MORAES%' OR 
UPPER(e.Texto) like '%ZILDA ALVES BARBOSA%' OR 
UPPER(e.Texto) like '%WEMBLEY BRAGA DA SILVA LIRA%' OR 
UPPER(e.Texto) like '%MARIA DO SOCORRO ALVES DOS SANTOS%' OR 
UPPER(e.Texto) like '%ELIONE FERNANDES PERES%' OR 
UPPER(e.Texto) like '%MANOEL ANTONIO DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA ROCILENE GOMES RODRIGUES%' OR 
UPPER(e.Texto) like '%LIONETE RODRIGUES DE CARVALHO%' OR 
UPPER(e.Texto) like '%JOSE DE ARIMATEIA BOAVENTURA DA SILVA%' OR 
UPPER(e.Texto) like '%FRANCISCO ALVES FRAGA%' OR 
UPPER(e.Texto) like '%ALEXANDRE DOS SANTOS SILVA%' OR 
UPPER(e.Texto) like '%MARCOS VINICIUS DOS SANTOS SOUZA%' OR 
UPPER(e.Texto) like '%LUCIMAR RIBEIRO DA SILVA%' OR 
UPPER(e.Texto) like '%EDCARLOS ALVES DA SILVA%' OR 
UPPER(e.Texto) like '%ELIANO ROGERIO DE LIMA%' OR 
UPPER(e.Texto) like '%LUCILENE DA SILVA NASCIMENTO%' OR 
UPPER(e.Texto) like '%SEBASTIAO SERGIO ONOFRE DE SOUZA%' OR 
UPPER(e.Texto) like '%FRANCISCO DAS CHAGAS TELES DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%COSMA NASCIMENTO DOS SANTOS%' OR 
UPPER(e.Texto) like '%JOSANGELA BANDEIRA DE FRANCA%' OR 
UPPER(e.Texto) like '%JOSANGELA BANDEIRA DE FRANCA%' OR 
UPPER(e.Texto) like '%ANTONIO PINTO DE LIMA%' OR 
UPPER(e.Texto) like '%NELSON ANASTACIO DE OLIVEIRA NETO%' OR 
UPPER(e.Texto) like '%FRANCISCA BRANDO DA COSTA%' OR 
UPPER(e.Texto) like '%PEDRO DA SILVA SALDANHA%' OR 
UPPER(e.Texto) like '%OCIVALDO SOUZA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%OCIVALDO SOUZA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%ANA MARIA DE SOUZA COSTA%' OR 
UPPER(e.Texto) like '%DANIEL ARAUJO MOREIRA%' OR 
UPPER(e.Texto) like '%WALDEMIR SALES MATOS%' OR 
UPPER(e.Texto) like '%MARCILIO LIMA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%JAILMA CAMPOS NASCIMENTO%' OR 
UPPER(e.Texto) like '%ELZANIR MARIA FALCAO DE FREITAS%' OR 
UPPER(e.Texto) like '%FRANCISCO CHAGAS FELIX DA SILVA%' OR 
UPPER(e.Texto) like '%ANTONIA ARAUJO DA SILVA%' OR 
UPPER(e.Texto) like '%SERGIO COELHO DA SILVA%' OR 
UPPER(e.Texto) like '%JULIO CEZAR MARQUES DA COSTA%' OR 
UPPER(e.Texto) like '%CREUSA SOARES DE SOUSA%' OR 
UPPER(e.Texto) like '%FRANCISCA VASQUES DA SILVA%' OR 
UPPER(e.Texto) like '%CARLOS DE SOUZA DIAS%' OR 
UPPER(e.Texto) like '%PAULO TEIXEIRA BEZERRA NETO%' OR 
UPPER(e.Texto) like '%MARIA ANTONIA DE OLIVEIRA FARIAS%' OR 
UPPER(e.Texto) like '%WALDEMAR ALVES FERREIRA%' OR 
UPPER(e.Texto) like '%MARIA DE OLIVEIRA CUNHA%' OR 
UPPER(e.Texto) like '%MARIA DE OLIVEIRA CUNHA%' OR 
UPPER(e.Texto) like '%EDILENE ENES LEBRE%' OR 
UPPER(e.Texto) like '%GENTIL DE CARLI%' OR 
UPPER(e.Texto) like '%MARIA DA CONCEICAO SANTOS DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA DA CONCEICAO SANTOS DA SILVA%' OR 
UPPER(e.Texto) like '%ANTONIO CLIDENOR BORGES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%FRANCISCO BARBOSA CAMILO%' OR 
UPPER(e.Texto) like '%TUPANIR DA COSTA LIMA%' OR 
UPPER(e.Texto) like '%ROSANIRA SOARES LIMA%' OR 
UPPER(e.Texto) like '%AMELIA GOMES PEREIRA DE SOUSA%' OR 
UPPER(e.Texto) like '%SEBASTIAO MORAIS DE CARVALHO%' OR 
UPPER(e.Texto) like '%ANTONIO FRANCISCO SILVA DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%MARIA LUIZA NOGUEIRA DE QUEIROZ%' OR 
UPPER(e.Texto) like '%ANTONIO VIEIRA DA SILVA%' OR 
UPPER(e.Texto) like '%OLIVIA DO ROSARIO PEREIRA DE SANTANA%' OR 
UPPER(e.Texto) like '%ANTONIA FLORENCIO DA CRUZ%' OR 
UPPER(e.Texto) like '%MARIA ZILMAR DE ALBUQUERQUE FILOMENO%' OR 
UPPER(e.Texto) like '%ZUFRAN CORREIA CAMPOS%' OR 
UPPER(e.Texto) like '%ANTONIO GUALBERTO DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA JANETE MOURA DA COSTA%' OR 
UPPER(e.Texto) like '%MARIA DAS GRACAS MESQUITA DE SOUZA%' OR 
UPPER(e.Texto) like '%JOSE MARIA TAVARES DE SOUZA%' OR 
UPPER(e.Texto) like '%ARLINDO FERREIRA DA CUNHA%' OR 
UPPER(e.Texto) like '%ARLINDO FERREIRA DA CUNHA%' OR 
UPPER(e.Texto) like '%DARCILA GONCALVES ESPINDOLA%' OR 
UPPER(e.Texto) like '%JAQUELINE BEZERRA BARBOSA%' OR 
UPPER(e.Texto) like '%MILTON INACIO%' OR 
UPPER(e.Texto) like '%MARIA DE NAZARE SOARES DA SILVA%' OR 
UPPER(e.Texto) like '%JEAN CARLOS BARBOSA DA SILVA%' OR 
UPPER(e.Texto) like '%ENOQUE PEREIRA MARINHO%' OR 
UPPER(e.Texto) like '%AGESILEIDE MAGALHAES DOS REIS%' OR 
UPPER(e.Texto) like '%SEBASTIAO NASCIMENTO DE SOUZA%' OR 
UPPER(e.Texto) like '%FRANCISCO PEREIRA MAIA%' OR 
UPPER(e.Texto) like '%MARIA DA CONCEICAO BENTO DE LIMA%' OR 
UPPER(e.Texto) like '%EDIVARDO DE LIMA RIOS%' OR 
UPPER(e.Texto) like '%EDIVARDO DE LIMA RIOS%' OR 
UPPER(e.Texto) like '%DINACI PINHEIRO DA SILVA NUNES%' OR 
UPPER(e.Texto) like '%PEDRO GIRAO DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%RAIMUNDA NONATA FREITAS DA SILVA%' OR 
UPPER(e.Texto) like '%EDIMILSON DA SILVA BARROSO%' OR 
UPPER(e.Texto) like '%MARIGERSIA BARROZO DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%MARINA MACHADO ARAUJO%' OR 
UPPER(e.Texto) like '%MARIA CLICIA COSTA DA SILVA%' OR 
UPPER(e.Texto) like '%NECIR LOPES DA SILVA NOGUEIRA%' OR 
UPPER(e.Texto) like '%ERCINEY VILELA DA SILVA%' OR 
UPPER(e.Texto) like '%ERCINEY VILELA DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA AUXILIADORA FREIRE DA SILVA%' OR 
UPPER(e.Texto) like '%FRANCISCO FIRMINO CAMPOS%' OR 
UPPER(e.Texto) like '%FRANCISCO FIRMINO CAMPOS%' OR 
UPPER(e.Texto) like '%CARLOS GEWILSON SIMAO AMANCIO%' OR 
UPPER(e.Texto) like '%CARLOS GEWILSON SIMAO AMANCIO%' OR 
UPPER(e.Texto) like '%JUCEIR VIEIRA DE FARIAS%' OR 
UPPER(e.Texto) like '%JOSE LUIZ SAMPAIO BEZERRA%' OR 
UPPER(e.Texto) like '%ALZEMIRA MENDES DA SILVA%' OR 
UPPER(e.Texto) like '%EDINAURA BARROS DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA ALBERINA ROQUE TAGLIRINA%' OR 
UPPER(e.Texto) like '%ANTONIO JOSE DE ALENCAR%' OR 
UPPER(e.Texto) like '%FRANCISCO GADELHA DE MENESES%' OR 
UPPER(e.Texto) like '%FRANCISCO SERGIO DA SILVA SOUZA%' OR 
UPPER(e.Texto) like '%MARIA EUGENIA DOS SANTOS MATOS%' OR 
UPPER(e.Texto) like '%CLARICE INES DE ALENCAR%' OR 
UPPER(e.Texto) like '%MANOEL CHARLES PIRES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%RAIMUNDO DA SILVA%' OR 
UPPER(e.Texto) like '%GRACILENE BENTO SENA%' OR 
UPPER(e.Texto) like '%GRACILENE BENTO SENA%' OR 
UPPER(e.Texto) like '%JAKELINE GOMES RIBEIRO%' OR 
UPPER(e.Texto) like '%HILCILEIDE SOUZA DA SILVEIRA%' OR 
UPPER(e.Texto) like '%ANTONIO DOS SANTOS FELIX%' OR 
UPPER(e.Texto) like '%DILSONEY CRISOSTOMO AMORIM%' OR 
UPPER(e.Texto) like '%ABSOLON LEAL DE CARVALHO%' OR 
UPPER(e.Texto) like '%SUZENI DERZE FERNANDES%' OR 
UPPER(e.Texto) like '%MARGARIDA LEMOS DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%EDINALDO SILVA DA COSTA%' OR 
UPPER(e.Texto) like '%MARIA TEREZINHA DA SILVA DE CARVALHO%' OR 
UPPER(e.Texto) like '%EURIDES DE SOUZA BATISTA%' OR 
UPPER(e.Texto) like '%JOCILENE D AVILA DA SILVA%' OR 
UPPER(e.Texto) like '%SEBASTIANA CLARINDO ANDRADE%' OR 
UPPER(e.Texto) like '%GLAUCIO SARAIVA DA SILVA%' OR 
UPPER(e.Texto) like '%NILO RODRIGUES DA COSTA%' OR 
UPPER(e.Texto) like '%PEDRO MESQUITA CARDOSO%' OR 
UPPER(e.Texto) like '%MARIA CANDIDA MONTEIRO%' OR 
UPPER(e.Texto) like '%ANALIA ANDRADE HOLANDA%' OR 
UPPER(e.Texto) like '%EDMILTON DA SILVA ROQUE NETO%' OR 
UPPER(e.Texto) like '%VLADMILSON MAIA DOS SANTOS%' OR 
UPPER(e.Texto) like '%VLADMILSON MAIA DOS SANTOS%' OR 
UPPER(e.Texto) like '%MARIA DE FATIMA DE SOUZA AMORIM%' OR 
UPPER(e.Texto) like '%ROCICLEB DA SILVA%' OR 
UPPER(e.Texto) like '%ROSIVALDO DE MACEDO BASTOS%' OR 
UPPER(e.Texto) like '%ROSIVALDO DE MACEDO BASTOS%' OR 
UPPER(e.Texto) like '%MARIA CRISTINA SANTOS DA SILVA%' OR 
UPPER(e.Texto) like '%LUCIA MARIA DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA GRACIETE GOMES DA COSTA%' OR 
UPPER(e.Texto) like '%MARIA DE JESUS SANTOS DE SOUZA%' OR 
UPPER(e.Texto) like '%JOAQUINA DA SILVA OLIVEIRA%' OR 
UPPER(e.Texto) like '%JAMYS LIMA ALMEIDA%' OR 
UPPER(e.Texto) like '%JOZIEL ALVES MOREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%ATILA CRISTINA CONCEICAO DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%SEBASTIAO SOARES DE MESQUITA%' OR 
UPPER(e.Texto) like '%LUIZ QUEIROZ DE SOUSA%' OR 
UPPER(e.Texto) like '%FRANCISCO DOMINGOS DA SILVA%' OR 
UPPER(e.Texto) like '%VAGNER CANDIDO DA SILVA%' OR 
UPPER(e.Texto) like '%EMILIO CAMINHA DE ALENCAR%' OR 
UPPER(e.Texto) like '%VERONICA SAMPAIO DOS SANTOS%' OR 
UPPER(e.Texto) like '%SUELI DERZE FERNANDES%' OR 
UPPER(e.Texto) like '%MARIA ARLENE DA COSTA MARTINS SANTOS%' OR 
UPPER(e.Texto) like '%RAIMUNDA DA SILVA FERREIRA%' OR 
UPPER(e.Texto) like '%MARIA CONSUELO MARTINS DE CASTRO%' OR 
UPPER(e.Texto) like '%FRANCISCO DIOGO RODRIGUES%' OR 
UPPER(e.Texto) like '%FRANCISCO DIOGO RODRIGUES%' OR 
UPPER(e.Texto) like '%RENATO DINIZ DA CRUZ COSTA%' OR 
UPPER(e.Texto) like '%RENATO DINIZ DA CRUZ COSTA%' OR 
UPPER(e.Texto) like '%MARIA VALDA PEREIRA DE SALES%' OR 
UPPER(e.Texto) like '%LUSMAR FREIRE DE CARVALHO%' OR 
UPPER(e.Texto) like '%ODETE DA SILVA MELO%' OR 
UPPER(e.Texto) like '%THEREZILDA PONTE PINHEIRO MOREIRA%' OR 
UPPER(e.Texto) like '%CARLOS DA SILVA VIEIRA%' OR 
UPPER(e.Texto) like '%MARIA SOCORRO PEREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%ROSANGELA MAGALHAES LIMA%' OR 
UPPER(e.Texto) like '%MARIA SOCORRO PEREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA MELO PINTO%' OR 
UPPER(e.Texto) like '%RAIMUNDO DAMAZIO DA SILVA FILHO%' OR 
UPPER(e.Texto) like '%RAIMUNDO DAMAZIO DA SILVA FILHO%' OR 
UPPER(e.Texto) like '%MARIA DE OLIVEIRA SILVA%' OR 
UPPER(e.Texto) like '%MARIA DE OLIVEIRA SILVA%' OR 
UPPER(e.Texto) like '%ROSA MARIA LIMA NEPOMUCENO%' OR 
UPPER(e.Texto) like '%ANTONIA MONTEIRO DE MESQUITA%' OR 
UPPER(e.Texto) like '%MARIA MARGARIDA DE ANDRADE LIRA%' OR 
UPPER(e.Texto) like '%JOVINA GOMES FERREIRA%' OR 
UPPER(e.Texto) like '%JOVINA GOMES FERREIRA%' OR 
UPPER(e.Texto) like '%JOSE MAGID KASSEM MASTUB%' OR 
UPPER(e.Texto) like '%FRANCISCA LIMA BEZERRA%' OR 
UPPER(e.Texto) like '%JOSE MAGID KASSEM MASTUB%' OR 
UPPER(e.Texto) like '%SHIRLENEY SOUSA LESSA%' OR 
UPPER(e.Texto) like '%NOMELIA MARIA GOMES RIBEIRO%' OR 
UPPER(e.Texto) like '%NOMELIA MARIA GOMES RIBEIRO%' OR 
UPPER(e.Texto) like '%FRANCISCO GOMES DA SILVA%' OR 
UPPER(e.Texto) like '%SEBASTIANA MARIA DE ARAUJO%' OR 
UPPER(e.Texto) like '%ANTONIO DA CONCEICAO LOPES%' OR 
UPPER(e.Texto) like '%ANTONIO RICARDO SOUZA DE LIMA%' OR 
UPPER(e.Texto) like '%JEANEA SOUZA DA SILVA%' OR 
UPPER(e.Texto) like '%JOSE RAIMUNDO BARBOSA RODRIGUES%' OR 
UPPER(e.Texto) like '%DAMIAO AZEVEDO DE SOUZA%' OR 
UPPER(e.Texto) like '%RAIMUNDA DOS SANTOS%' OR 
UPPER(e.Texto) like '%EDIVALDO AGUIAR DE LIMA%' OR 
UPPER(e.Texto) like '%MARIA RODRIGUES DE CASTRO%' OR 
UPPER(e.Texto) like '%VALDECI BARROSO DA CRUZ%' OR 
UPPER(e.Texto) like '%VALDECI BARROSO DA CRUZ%' OR 
UPPER(e.Texto) like '%FRANCISCA DA SILVA LIMA%' OR 
UPPER(e.Texto) like '%AMARILDO MESQUITA DOS REIS%' OR 
UPPER(e.Texto) like '%MARIA DARCI DE ARAUJO%' OR 
UPPER(e.Texto) like '%QUIRINO ARAUJO CORDEIRO%' OR 
UPPER(e.Texto) like '%QUIRINO ARAUJO CORDEIRO%' OR 
UPPER(e.Texto) like '%SALETE NASCIMENTO DOS SANTOS%' OR 
UPPER(e.Texto) like '%MARIA LUIZA MESQUITA DE SOUZA%' OR 
UPPER(e.Texto) like '%JOSE PAULO DE MAGALHAES%' OR 
UPPER(e.Texto) like '%SEBASTIAO DE OLIVEIRA MAIA%' OR 
UPPER(e.Texto) like '%OZEMIR ALMEIDA DA SILVA%' OR 
UPPER(e.Texto) like '%RUBENS DE GOES RIBEIRO%' OR 
UPPER(e.Texto) like '%MARIA DO SOCORRO BARBOSA DE FREITAS%' OR 
UPPER(e.Texto) like '%MARIA JULIA PLUMA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%MARIA BATISTA DE ANDRADE%' OR 
UPPER(e.Texto) like '%DAMIAO ARAUJO DE LIMA%' OR 
UPPER(e.Texto) like '%FRANCISCA CARLOS CORREA DA ROCHA%' OR 
UPPER(e.Texto) like '%FRANCISCO DUARTE FIGUEREDO%' OR 
UPPER(e.Texto) like '%VANIA RICARDO DE LEMOS%' OR 
UPPER(e.Texto) like '%VANIA RICARDO DE LEMOS%' OR 
UPPER(e.Texto) like '%MARIA LUZIA SANTOS DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%ANGELA MARIA DA SILVA LEITE%' OR 
UPPER(e.Texto) like '%CHEILA DE CASTRO DA SILVA%' OR 
UPPER(e.Texto) like '%FRANCISCO NERY BEZERRA%' OR 
UPPER(e.Texto) like '%MARIA BRAZ DA SILVA%' OR 
UPPER(e.Texto) like '%RAIMUNDA HELENA DAS CHAGAS MOURAO RODRIGUES%' OR 
UPPER(e.Texto) like '%JUSCELINO PEREIRA DA COSTA%' OR 
UPPER(e.Texto) like '%ALDERLEI DA PASCOA MONTEIRO%' OR 
UPPER(e.Texto) like '%JUTACY ANTONIO SOUZA DOS SANTOS%' OR 
UPPER(e.Texto) like '%LUIZ PEREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%LUIZ PEREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%ALZIRA LIMA ALMEIDA%' OR 
UPPER(e.Texto) like '%ROSSILEUDO COSTA DOS SANTOS%' OR 
UPPER(e.Texto) like '%FELIPE GOMES CAVALCANTE%' OR 
UPPER(e.Texto) like '%JOSE GOMES DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA HELENA GONCALVES SALES%' OR 
UPPER(e.Texto) like '%JOSE DE ALMEIDA LIRA%' OR 
UPPER(e.Texto) like '%IENE VELARDE OJOPI%' OR 
UPPER(e.Texto) like '%IENE VELARDE OJOPI%' OR 
UPPER(e.Texto) like '%ROSA MARIA RIOS DE SOUZA%' OR 
UPPER(e.Texto) like '%FRANCISCA MARIA CAMARGO DE ARAUJO%' OR 
UPPER(e.Texto) like '%SILVANA DA CUNHA ALMEIDA%' OR 
UPPER(e.Texto) like '%MARIA DO ROSARIO PEREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA RIBEIRO MOTA%' OR 
UPPER(e.Texto) like '%MARIA JOSE MARTINS FREIRE%' OR 
UPPER(e.Texto) like '%JOSE MARIA DE FREITAS MOREIRA%' OR 
UPPER(e.Texto) like '%JOSE MARIA DE FREITAS MOREIRA%' OR 
UPPER(e.Texto) like '%ANTONIO NONATO DE MENEZES LIMA%' OR 
UPPER(e.Texto) like '%JAYME TAGLIARINE JUNIOR%' OR 
UPPER(e.Texto) like '%JOEL DA SILVA ALENCAR%' OR 
UPPER(e.Texto) like '%ANTONIO CARDOSO DOS SANTOS%' OR 
UPPER(e.Texto) like '%JOSE PEREIRA DE MESQUITA%' OR 
UPPER(e.Texto) like '%ROSA DO NASCIMENTO ABREU%' OR 
UPPER(e.Texto) like '%CLEMIR BARRETO DE ALMEIDA%' OR 
UPPER(e.Texto) like '%NONATO BERNARDO DE SOUZA%' OR 
UPPER(e.Texto) like '%PEDRO FRANCO DE ARRUDA%' OR 
UPPER(e.Texto) like '%PEDRO FRANCO DE ARRUDA%' OR 
UPPER(e.Texto) like '%JOSE MARIA TELS DE SOUZA%' OR 
UPPER(e.Texto) like '%IACI PEREIRA DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%FRANCISCO ALVES DA SILVA%' OR 
UPPER(e.Texto) like '%KEMMIL DE MELO COELHO%' OR 
UPPER(e.Texto) like '%FRANCISCO NUNES PEREIRA%' OR 
UPPER(e.Texto) like '%FRANCISCO NUNES PEREIRA%' OR 
UPPER(e.Texto) like '%CREUZA ALVES DE FRANCA%' OR 
UPPER(e.Texto) like '%SEBASTIANA RIBEIRO TAMARANA%' OR 
UPPER(e.Texto) like '%MARIA DAS NEVES SOARES DA SILVA%' OR 
UPPER(e.Texto) like '%OZANI DO NASCIMENTO ABREU%' OR 
UPPER(e.Texto) like '%FRANCISCO AFONSO DA SILVA TOJAL%' OR 
UPPER(e.Texto) like '%SEBASTIAO MARQUES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%NONATO DE OLIVEIRA SOARES%' OR 
UPPER(e.Texto) like '%ALAISE FERREIRA DE LIMA%' OR 
UPPER(e.Texto) like '%ANTONIA ALDA DA SILVA LIMA%' OR 
UPPER(e.Texto) like '%FRANCISCO DA SILVA OLIVEIRA%' OR 
UPPER(e.Texto) like '%CORINA PINTO CAMPOS TAVARES%' OR 
UPPER(e.Texto) like '%EDJANE LIMA DA SILVA%' OR 
UPPER(e.Texto) like '%LINDAURA DOS SANTOS OLIVEIRA%' OR 
UPPER(e.Texto) like '%IZAILDA DO NASCIMENTO SILVA%' OR 
UPPER(e.Texto) like '%CARLOS ALBERTO DE OLIVEIRA MORAES%' OR 
UPPER(e.Texto) like '%TEREZINHA ALVES DA SILVA%' OR 
UPPER(e.Texto) like '%RAIMUNDA PERES DE MORAES%' OR 
UPPER(e.Texto) like '%RODINEI DE OLIVEIRA NUNES%' OR 
UPPER(e.Texto) like '%EDIZIO FERREIRA LIMA%' OR 
UPPER(e.Texto) like '%ANGELA MARIA DA SILVA%' OR 
UPPER(e.Texto) like '%JOSE MATOS DA SILVA%' OR 
UPPER(e.Texto) like '%LUCILENE SOUZA DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA DAS GRACAS DE OLIVEIRA BRAGA%' OR 
UPPER(e.Texto) like '%FRANCISCO FERREIRA DE ANDRADE%' OR 
UPPER(e.Texto) like '%MARCOS FERNANDO DE SOUZA%' OR 
UPPER(e.Texto) like '%CLEZIO DE FREITAS MOREIRA%' OR 
UPPER(e.Texto) like '%GEDI ROCHA DE ANDRADE%' OR 
UPPER(e.Texto) like '%AMANDA SEBASTIANA CARVALHOSA DE SOUSA%' OR 
UPPER(e.Texto) like '%IVANILDE FERREIRA DE MOURA%' OR 
UPPER(e.Texto) like '%GOLDENEIR BARROSO DE FREITAS%' OR 
UPPER(e.Texto) like '%SUELI FERREIRA ADVINCULA%' OR 
UPPER(e.Texto) like '%SAMUEL DE LIMA MOTA%' OR 
UPPER(e.Texto) like '%FRANCISCA SOUSA LESSA%' OR 
UPPER(e.Texto) like '%ALUIZIO DA LUZ%' OR 
UPPER(e.Texto) like '%JULIETA GOMES DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA DE NAZARE GOMES RIBEIRO%' OR 
UPPER(e.Texto) like '%LAURO VIEIRA LIMA%' OR 
UPPER(e.Texto) like '%LAURO VIEIRA LIMA%' OR 
UPPER(e.Texto) like '%ALZEMIR DE SOUZA BATISTA%' OR 
UPPER(e.Texto) like '%HERMINIO RAMOS DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%ADEM ARAUJO DA SILVA%' OR 
UPPER(e.Texto) like '%ELILDA FIRMINO CAMPOS%' OR 
UPPER(e.Texto) like '%ELILDA FIRMINO CAMPOS%' OR 
UPPER(e.Texto) like '%RAIMUNDO MARTINS DE LIMA%' OR 
UPPER(e.Texto) like '%EUDILENE OLIVEIRA DE MELO%' OR 
UPPER(e.Texto) like '%EMILTON PEREIRA LIMA%' OR 
UPPER(e.Texto) like '%MIRACY BEZERRA DOS SANTOS%' OR 
UPPER(e.Texto) like '%OSMIRO SIQUEIRA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%ARLINDO GALDINO DA SILVA%' OR 
UPPER(e.Texto) like '%FRANCISCO COSTA DA SILVA%' OR 
UPPER(e.Texto) like '%ALCENIRA MOTA BASTOS%' OR 
UPPER(e.Texto) like '%VALCIONE OLIVEIRA DA ROCHA%' OR 
UPPER(e.Texto) like '%VANIA MARIA DE SOUZA ADVINCULA%' OR 
UPPER(e.Texto) like '%EDINALVA DE LIMA FONSECA DE SOUZA%' OR 
UPPER(e.Texto) like '%MARIA FRANCILENE PONTES DA SILVA%' OR 
UPPER(e.Texto) like '%ROBERTO CARLOS MACIEL ALVES%' OR 
UPPER(e.Texto) like '%EUNICE GOMES DE LIMA%' OR 
UPPER(e.Texto) like '%JOSE AILTON MACIEL DE LIMA%' OR 
UPPER(e.Texto) like '%ANGELINA TABOSA NOGUEIRA%' OR 
UPPER(e.Texto) like '%ANGELINA TABOSA NOGUEIRA%' OR 
UPPER(e.Texto) like '%FRANCISCO CARLOS OLIVEIRA DA CRUZ%' OR 
UPPER(e.Texto) like '%PAULO SERGIO DE FREITAS%' OR 
UPPER(e.Texto) like '%ANTONIO BARBOSA LOPES%' OR 
UPPER(e.Texto) like '%JANY DEROMEDIS LOPES%' OR 
UPPER(e.Texto) like '%FRANCISCO DE JESUS LIMA DE ARAUJO%' OR 
UPPER(e.Texto) like '%NATALIA MARIA LUCAS DA FONSECA%' OR 
UPPER(e.Texto) like '%EUZIR RODRIGUES DA SILVA%' OR 
UPPER(e.Texto) like '%FRANCISCO DE ASSIS OLIVEIRA DE MENDONCA%' OR 
UPPER(e.Texto) like '%ANTONIETA LANDIM DA SILVA%' OR 
UPPER(e.Texto) like '%ANAIUDO CORDEIRO DA SILVA%' OR 
UPPER(e.Texto) like '%ROSINEIDE DE LIMA APRIJO%' OR 
UPPER(e.Texto) like '%ZENEIDE ALVES BARBOSA%' OR 
UPPER(e.Texto) like '%DOUGLAS JONATHAN SANTIAGO SOUZA%' OR 
UPPER(e.Texto) like '%CHEILA MARIA SOUZA DAS NEVES%' OR 
UPPER(e.Texto) like '%WILSON JOSE ESTEVAM DE SOUZA%' OR 
UPPER(e.Texto) like '%MARIA FRANCINEIDE TELES DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%MARIA LUCILENE DO NASCIMENTO FREITAS%' OR 
UPPER(e.Texto) like '%JANES CARLOS MESQUITA DA CRUZ%' OR 
UPPER(e.Texto) like '%ELIZA CALISTA DE ANDRADE%' OR 
UPPER(e.Texto) like '%MARIA DE JESUS DA SILVA NASCIMENTO%' OR 
UPPER(e.Texto) like '%DAMARES BARROS DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%RONILSON JANUARIO DA SILVA%' OR 
UPPER(e.Texto) like '%MARTA GOMES DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA JOSE FERREIRA LIMA%' OR 
UPPER(e.Texto) like '%PEDRO LIMA DA ROCHA%' OR 
UPPER(e.Texto) like '%PEDRO LIMA DA ROCHA%' OR 
UPPER(e.Texto) like '%PEREGRINO ROCHA DOS SANTOS%' OR 
UPPER(e.Texto) like '%RONED DE OLIVEIRA SILVA%' OR 
UPPER(e.Texto) like '%RONED DE OLIVEIRA SILVA%' OR 
UPPER(e.Texto) like '%ANTONIO AFONSO SILVA DE SALES%' OR 
UPPER(e.Texto) like '%JOSE PINHEIRO DE CARVALHO%' OR 
UPPER(e.Texto) like '%MARIA IRACEMA MAGALHAES DOS SANTOS%' OR 
UPPER(e.Texto) like '%MANOEL NAZARENO RODRIGUES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%MANOEL NAZARENO RODRIGUES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%CESAR DA SILVA PRAXEDES%' OR 
UPPER(e.Texto) like '%MARIA FRANCILEIDE PONTES DA SILVA%' OR 
UPPER(e.Texto) like '%ANTONIA DA SILVA SOUZA%' OR 
UPPER(e.Texto) like '%RAIMUNDO DE SOUZA MENDES%' OR 
UPPER(e.Texto) like '%MARIA ELIANA TELES DOURADO%' OR 
UPPER(e.Texto) like '%ROBERTO MACIEL DE MEDEIROS%' OR 
UPPER(e.Texto) like '%ADEMIR VASCONCELOS PINHEIRO%' OR 
UPPER(e.Texto) like '%ROSIALDO NUNES DA SILVA%' OR 
UPPER(e.Texto) like '%SIFRONIO BEZERRA DA SILVA%' OR 
UPPER(e.Texto) like '%ROCILEDO DA COSTA SANTOS%' OR 
UPPER(e.Texto) like '%MARIA MARGARIDA PORFIRIO MACEDO%' OR 
UPPER(e.Texto) like '%VILSON BARRETO DA SILVA%' OR 
UPPER(e.Texto) like '%VALCILENE AZEVEDO DE MATOS%' OR 
UPPER(e.Texto) like '%ELCIMAR DA SILVA SANTOS%' OR 
UPPER(e.Texto) like '%MARIA ANTONIA DE OLIVEIRA ROCHA%' OR 
UPPER(e.Texto) like '%LEA JOAQUINA DA SILVA%' OR 
UPPER(e.Texto) like '%RAIMUNDO LAESIO DA SILVA SOUZA%' OR 
UPPER(e.Texto) like '%RAIMUNDA SILVA DE ALMEIDA%' OR 
UPPER(e.Texto) like '%RAIMUNDO GOMES DE PAULA%' OR 
UPPER(e.Texto) like '%NAZARE JUCA DE MIRANDA%' OR 
UPPER(e.Texto) like '%SEBASTIAO VALTER DA SILVA%' OR 
UPPER(e.Texto) like '%SEBASTIAO VALTER DA SILVA%' OR 
UPPER(e.Texto) like '%CLEONICE NASCIMENTO DA SILVA%' OR 
UPPER(e.Texto) like '%DACILENE ARAUJO DA SILVA%' OR 
UPPER(e.Texto) like '%JOAO ALVES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%ELDA DO NASCIMENTO ABREU%' OR 
UPPER(e.Texto) like '%MARCOS ROBERTO DE SOUZA MORAES%' OR 
UPPER(e.Texto) like '%ALDENIRA LIMA COSTA%' OR 
UPPER(e.Texto) like '%MANOEL MESSIAS DE OLIVEIRA CASTRO%' OR 
UPPER(e.Texto) like '%FRANCISCA MESQUITA DE SOUZA%' OR 
UPPER(e.Texto) like '%MARCELO FACUNDO DE CARVALHO%' OR 
UPPER(e.Texto) like '%EFRAIM LIMA DA SILVA%' OR 
UPPER(e.Texto) like '%RAIMUNDO NONATO PINTO CAMPOS%' OR 
UPPER(e.Texto) like '%ANTONIO ARAUJO BARROS%' OR 
UPPER(e.Texto) like '%MARIA ALCILENE DE OLIVEIRA MIRANDA%' OR 
UPPER(e.Texto) like '%ANTONIO LUSTOZO FILISMINO DA SILVA%' OR 
UPPER(e.Texto) like '%RAIMUNDO NONATO DA SILVA%' OR 
UPPER(e.Texto) like '%FRANCISCA DE OLIVEIRA ASSUNCAO%' OR 
UPPER(e.Texto) like '%FRANCISCA ANTONIA MESQUITA DE SOUZA%' OR 
UPPER(e.Texto) like '%MARIA ELAYNE PEPES GOMES%' OR 
UPPER(e.Texto) like '%PAULO FRANCO TELES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%JOSETE FARIAS DE LIMA%' OR 
UPPER(e.Texto) like '%LAERCIO PEDRO GOMES DA SILVA%' OR 
UPPER(e.Texto) like '%ABDIAS FERREIRA DE LIMA%' OR 
UPPER(e.Texto) like '%SIRLA DE MENDONCA DINIZ%' OR 
UPPER(e.Texto) like '%FRANCISCO NASCIMENTO SILVA%' OR 
UPPER(e.Texto) like '%RAIMUNDO ENEAS LIMA%' OR 
UPPER(e.Texto) like '%MARIA ANGELICA DA CONCEICAO ARAUJO DE SOUZA%' OR 
UPPER(e.Texto) like '%SHIRLEY MARIA FERREIRA DE PAULA%' OR 
UPPER(e.Texto) like '%ELARDO RUI PERES%' OR 
UPPER(e.Texto) like '%ANTONIO DE OLIVEIRA MAIA%' OR 
UPPER(e.Texto) like '%JOSE CARLOS AGRIPINO DE SOUZA%' OR 
UPPER(e.Texto) like '%JOSE MARIA BARBOSA DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%ANTONIO DE SOUZA IBIAPINA%' OR 
UPPER(e.Texto) like '%AMILCAR DA SILVA ARAUJO%' OR 
UPPER(e.Texto) like '%JOSELI GUEDES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%RAIMUNDO CORREA DE LIMA NETO%' OR 
UPPER(e.Texto) like '%VALTER RUIZ RIOS%' OR 
UPPER(e.Texto) like '%ROSEANE DA SILVA COSTA%' OR 
UPPER(e.Texto) like '%GILVANE SOUZA DA ROCHA%' OR 
UPPER(e.Texto) like '%BENEDITO GUILHERME DE SOUZA%' OR 
UPPER(e.Texto) like '%ODARINO CANUTO DA SILVA%' OR 
UPPER(e.Texto) like '%GILBERTO OLIVEIRA DA SILVA%' OR 
UPPER(e.Texto) like '%WELITON DE ALENCAR ALMEIDA%' OR 
UPPER(e.Texto) like '%ERLANGELA DA COSTA LIMA%' OR 
UPPER(e.Texto) like '%JOSE LOPES DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA CONCEICAO FERNANDES PERES%' OR 
UPPER(e.Texto) like '%VALOIZA DE SOUZA DIAS%' OR 
UPPER(e.Texto) like '%VALOIZA DE SOUZA DIAS%' OR 
UPPER(e.Texto) like '%FRANCISCO DE ASSIS ROCHA DE MELO%' OR 
UPPER(e.Texto) like '%JOAO JOSE MIRANDA GOMES%' OR 
UPPER(e.Texto) like '%ELCIVANDO FERREIRA DA SILVA SIMAO%' OR 
UPPER(e.Texto) like '%CAIRO ROBERTO PEREIRA%' OR 
UPPER(e.Texto) like '%EVANIR SEVERINO DA SILVA%' OR 
UPPER(e.Texto) like '%ALCIDES DA SILVA OLIVEIRA%' OR 
UPPER(e.Texto) like '%LUZIA CAVALCANTE DA SILVA%' OR 
UPPER(e.Texto) like '%DOLAIR FATIMA ROCHA DOS SANTOS%' OR 
UPPER(e.Texto) like '%ZULIMA DA SILVA MARTINS%' OR 
UPPER(e.Texto) like '%MARINA MARTINS DE LIMA%' OR 
UPPER(e.Texto) like '%JOSE CARLOS DA SILVA COSTA%' OR 
UPPER(e.Texto) like '%JOSE CARLOS DA SILVA COSTA%' OR 
UPPER(e.Texto) like '%MARIA DO NASCIMENTO DIAS%' OR 
UPPER(e.Texto) like '%MARIA DAS GRACAS MENDONCA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%ANTONIO DE OLIVEIRA SILVA%' OR 
UPPER(e.Texto) like '%JOCILENE ALVES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%JOCILENE ALVES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%MARCIO LEANDRO LIMA DE SOUZA%' OR 
UPPER(e.Texto) like '%ROSSI COSTA DOS SANTOS%' OR 
UPPER(e.Texto) like '%CARLOS MAIA DE MORAES%' OR 
UPPER(e.Texto) like '%EDVALDO ALMEIDA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%EDMILSON FALCAO DE QUEIRÓZ%' OR 
UPPER(e.Texto) like '%ADELAINE DE OLIVEIRA ALMEIDA%' OR 
UPPER(e.Texto) like '%ANTONIO FRANCISCO BEZERRA DA SILVA%' OR 
UPPER(e.Texto) like '%ANTONIO SOUZA DA SILVA SANTOS%' OR 
UPPER(e.Texto) like '%RORAYMA MATOS DA SILVA%' OR 
UPPER(e.Texto) like '%FRANCISCO CHAGAS DA SILVA%' OR 
UPPER(e.Texto) like '%DELIZARTE LOPES DA SILVA%' OR 
UPPER(e.Texto) like '%FRANCISCO FERNANDES DE ALMEIDA%' OR 
UPPER(e.Texto) like '%RAILDA DA SILVA NEPOMUCENO PEREIRA%' OR 
UPPER(e.Texto) like '%ALBERTINA OLIMPIO DA SILVA%' OR 
UPPER(e.Texto) like '%CLARICE BEZERRA DE MENDONCA%' OR 
UPPER(e.Texto) like '%MARIA NASCIMENTO DE AZEVEDO%' OR 
UPPER(e.Texto) like '%MARIA DAS GRACAS BATISTA DE MELO%' OR 
UPPER(e.Texto) like '%MARINA XAVIER DA COSTA%' OR 
UPPER(e.Texto) like '%ESPERIDIAO DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%CLAUDINA FREITAS DA SILVA%' OR 
UPPER(e.Texto) like '%EVA MARIA GOMES RODRIGUES%' OR 
UPPER(e.Texto) like '%MARIZAN DA SILVA LIMA%' OR 
UPPER(e.Texto) like '%MARIZAN DA SILVA LIMA%' OR 
UPPER(e.Texto) like '%JORGINA LIMA DA SILVA%' OR 
UPPER(e.Texto) like '%EZEQUIEL DE ARAUJO MARQUES%' OR 
UPPER(e.Texto) like '%VERONICA ALBINA DE LIMA%' OR 
UPPER(e.Texto) like '%FRANCISCA PAIVA DE SOUZA%' OR 
UPPER(e.Texto) like '%ANTONIA FERREIRA GOMES%' OR 
UPPER(e.Texto) like '%MARILZA DA SILVA SOUZA%' OR 
UPPER(e.Texto) like '%ALAN KARDEK DOS SANTOS ASSUNCAO%' OR 
UPPER(e.Texto) like '%JESSE RODRIGUES FARIAS%' OR 
UPPER(e.Texto) like '%CAREM PEREIRA LIMA DE CARVALHO%' OR 
UPPER(e.Texto) like '%FRANCISCA PAIVA DE SOUZA%' OR 
UPPER(e.Texto) like '%DINIS SENHORINHA DE ALENCAR%' OR 
UPPER(e.Texto) like '%FRANCISCO GLEYSON DA SILVA FRANCA%' OR 
UPPER(e.Texto) like '%RENATO DE BARROS RODRIGUES%' OR 
UPPER(e.Texto) like '%RAIMUNDO DAMASIO SILVA%' OR 
UPPER(e.Texto) like '%PEDRO REBOUCAS DA COSTA%' OR 
UPPER(e.Texto) like '%LUIZ SILVA SOUZA%' OR 
UPPER(e.Texto) like '%MARIA ROCIMILDA MOREIRA BEZERRA DE SOUZA%' OR 
UPPER(e.Texto) like '%GERALDO RAFAEL DE SOUSA%' OR 
UPPER(e.Texto) like '%ISMAEL ALVES BANDEIRA%' OR 
UPPER(e.Texto) like '%RENATO DE BARROS RODRIGUES%' OR 
UPPER(e.Texto) like '%ZARIF CARVALHO MASTUB FILGUEIRAS%' OR 
UPPER(e.Texto) like '%MARIA SANTOS DA SILVA%' OR 
UPPER(e.Texto) like '%ANTONIO MARIA MESQUITA DE SOUZA%' OR 
UPPER(e.Texto) like '%JOAO NICOLAU SOARES RODRIGUES%' OR 
UPPER(e.Texto) like '%JOSE MARTINS DA SILVA%' OR 
UPPER(e.Texto) like '%SHIRLEI SOUSA LESSA%' OR 
UPPER(e.Texto) like '%JOSE LUIZ SOUZA DA SILVA%' OR 
UPPER(e.Texto) like '%JONAS LEANDRO DE SOUZA%' OR 
UPPER(e.Texto) like '%ADILSON PEREIRA CHARIFE%' OR 
UPPER(e.Texto) like '%GILBERTO ARAUJO DE CASTRO%' OR 
UPPER(e.Texto) like '%VALDINEIA ROCHA DA SILVA%' OR 
UPPER(e.Texto) like '%SONIA NERES GOUVEIA%' OR 
UPPER(e.Texto) like '%MARIA DE LOURDES VIANA FONTENELE%' OR 
UPPER(e.Texto) like '%CLEUDINA GOMES RIBEIRO%' OR 
UPPER(e.Texto) like '%YARA PURANGA DE ABUNAM%' OR 
UPPER(e.Texto) like '%GERALDO PEREIRA DE ARAUJO%' OR 
UPPER(e.Texto) like '%EDINALDO MACHADO MOREIRA%' OR 
UPPER(e.Texto) like '%JAILSON SALDANHA NOGUEIRA%' OR 
UPPER(e.Texto) like '%TEREZA PERES BARBOSA CAVALCANTE%' OR 
UPPER(e.Texto) like '%DAMAZIO PAULO DA COSTA%' OR 
UPPER(e.Texto) like '%FRANCISCO FERREIRA CHAVES%' OR 
UPPER(e.Texto) like '%ANIBAL BARBOSA LOPES%' OR 
UPPER(e.Texto) like '%EDILEUZA PORFIRIO DA COSTA%' OR 
UPPER(e.Texto) like '%RAIMUNDO OSVALDO RODRIGUES DE SOUZA%' OR 
UPPER(e.Texto) like '%DAMASIO PEREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%LORENA LEAL DE ARAUJO%' OR 
UPPER(e.Texto) like '%LINOLENE ALESANDRA DA SILVA LIRA SANTOS%' OR 
UPPER(e.Texto) like '%RAYMAR PEREIRA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%RAYMAR PEREIRA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%AILTON VIANA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%ANTONIA ALDERLENE DE FREITAS%' OR 
UPPER(e.Texto) like '%MARIA DO CARMO ALMEIDA SANTIAGO%' OR 
UPPER(e.Texto) like '%EDMILSON NEGREIROS DA SILVA%' OR 
UPPER(e.Texto) like '%EDNA DA COSTA MACEDO%' OR 
UPPER(e.Texto) like '%JORGE LUIZ ARAUJO BARROS%' OR 
UPPER(e.Texto) like '%HELEN CRISTINA VAZ DE MEDEIROS%' OR 
UPPER(e.Texto) like '%DIVA SANTANA DE SOUZA%' OR 
UPPER(e.Texto) like '%FERNANDO PAIVA DO NASCIMENTO%' OR 

UPPER(e.Texto) like '%ADERSON VIEIRA LIMA%' OR 
UPPER(e.Texto) like '%PASCO BELO DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA JOSE EVANGELISTA DA CUNHA%' OR 
UPPER(e.Texto) like '%NIZIO RUI PERES%' OR 
UPPER(e.Texto) like '%ROBERVAL JUNQUEIRA%' OR 
UPPER(e.Texto) like '%RAIMUNDO NOBRE FERREIRA%' OR 
UPPER(e.Texto) like '%MARIA LEONILDE FERREIRA MARTINS%' OR 
UPPER(e.Texto) like '%AURILIA BENEDITA DA SILVA%' OR 
UPPER(e.Texto) like '%JORGE ALCANTRA CUNHA%' OR 
UPPER(e.Texto) like '%ELIODEDE DE FREITAS GOMES%' OR 
UPPER(e.Texto) like '%SANDRA AMORIM LEITE%' OR 
UPPER(e.Texto) like '%EVALDO PERES RIOS%' OR 
UPPER(e.Texto) like '%JOSE RIBAMAR PEREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%FRANCISCA LANUSIA SANTOS DA SILVA%' OR 
UPPER(e.Texto) like '%AGIVALDO DE ARAUJO LIMA%' OR 
UPPER(e.Texto) like '%ACLELSON SANTOS DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%JOSE RIBAMAR PEREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%VLADIMIR ALMEIDA DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%MARCOS SIQUEIRA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%ANTONIO MANOEL GOMES DA SILVA%' OR 
UPPER(e.Texto) like '%CARLOS ALBERTO GREGORIO ALVES%' OR 
UPPER(e.Texto) like '%IDELIZIA SOARES DOS SANTOS%' OR 
UPPER(e.Texto) like '%TEREZINHA RODRIGUES BARBOZA%' OR 
UPPER(e.Texto) like '%RAIMUNDA SOUZA DA SILVA%' OR 
UPPER(e.Texto) like '%ANTONIO AMBROSIO DE LIMA%' OR 
UPPER(e.Texto) like '%FRANCISCO DE ASSIS LIMA DIAS%' OR 
UPPER(e.Texto) like '%FRANCISCO DE ASSIS LIMA DIAS%' OR 
UPPER(e.Texto) like '%RAIMUNDO RIOS SALDANHA%' OR 
UPPER(e.Texto) like '%ROBERTO RODRIGUES CASAS%' OR 
UPPER(e.Texto) like '%NAZARE BRITO DE ARAUJO%' OR 
UPPER(e.Texto) like '%NAZARE BRITO DE ARAUJO%' OR 
UPPER(e.Texto) like '%JOSSENILSON DA COSTA MOREIRA%' OR 
UPPER(e.Texto) like '%NEIVALDO MOREIRA LEITAO%' OR 
UPPER(e.Texto) like '%FRANCISCO CLAUDECIR SILVA DA COSTA%' OR 
UPPER(e.Texto) like '%EURICO JORGE DE SOUZA%' OR 
UPPER(e.Texto) like '%MIRTES DO NASCIMENTO ABREU%' OR 
UPPER(e.Texto) like '%MARIA JOSE PEREIRA DE MOURA%' OR 
UPPER(e.Texto) like '%FRANCISCO EUGENIO DE SOUZA%' OR 
UPPER(e.Texto) like '%JOSE CARLOS GOMES DA SILVA%' OR 
UPPER(e.Texto) like '%JAMES DE OLIVEIRA PAIVA%' OR 
UPPER(e.Texto) like '%JOSE OSMINDO PINHEIRO SANTOS%' OR 
UPPER(e.Texto) like '%EDVALDO ESTACIO DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA BENICE CAVALCANTE DA SILVA%' OR 
UPPER(e.Texto) like '%PERPEDIQUINA FERREIRA DE ANDRADE%' OR 
UPPER(e.Texto) like '%FRANCISCO LIMA DA SILVA%' OR 
UPPER(e.Texto) like '%ANTONIO FRANCISCO MARQUES DE SOUSA%' OR 
UPPER(e.Texto) like '%MESSIAS LOPES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%SUNAMETA GALDINO DA SILVA%' OR 
UPPER(e.Texto) like '%ANABELA DA SILVEIRA ALMEIDA%' OR 
UPPER(e.Texto) like '%JOSE RODRIGUES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%JOSE RODRIGUES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%ANTONIO JOSE LAUREANO DA SILVA%' OR 
UPPER(e.Texto) like '%ANTONIO JOSE LAUREANO DA SILVA%' OR 
UPPER(e.Texto) like '%ROSIMEIRE GAMA CHAVES%' OR 
UPPER(e.Texto) like '%ECINAIRO DA SILVA CARVALHO%' OR 
UPPER(e.Texto) like '%MARIA MATOS DA COSTA%' OR 
UPPER(e.Texto) like '%MANOEL BENEDITO PEREIRA DE MELO%' OR 
UPPER(e.Texto) like '%LAZARO FEITOSA DO CARMO%' OR 
UPPER(e.Texto) like '%FRANCINETE DE SOUZA FERNANDES%' OR 
UPPER(e.Texto) like '%MARIA AUXILIADORA RAMOS DE SOUZA%' OR 
UPPER(e.Texto) like '%RUBIN FREIRE DA SILVA%' OR 
UPPER(e.Texto) like '%FRANCISCO MAIA BANDEIRA%' OR 
UPPER(e.Texto) like '%EDELADIO BARBOSA DE SOUZA%' OR 
UPPER(e.Texto) like '%CELY PEREIRA GUERRA%' OR 
UPPER(e.Texto) like '%LUCIENE DA SILVA NASCIMENTO%' OR 
UPPER(e.Texto) like '%EUNICE MOREIRA DE FARIAS%' OR 
UPPER(e.Texto) like '%JARBAS CHALUB DOS SANTOS%' OR 
UPPER(e.Texto) like '%MARIA DA CONCEICAO ALVES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%MARIA ABINOAN FREITAS BRANDAO%' OR 
UPPER(e.Texto) like '%ANTONIA PEREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%RAIMUNDO FERNANDES DE SOUZA%' OR 
UPPER(e.Texto) like '%HEDILEUDO ASSUNCAO MARQUES%' OR 
UPPER(e.Texto) like '%MARIA MARTA BARRETO DA SILVA%' OR 
UPPER(e.Texto) like '%FRANCISCO OLIVEIRA DA SILVA%' OR 
UPPER(e.Texto) like '%CLEMILTO PINTO CAMPOS%' OR 
UPPER(e.Texto) like '%WALTER NUNES DA LUZ%' OR 
UPPER(e.Texto) like '%ADEMIR PEREIRA SALES%' OR 
UPPER(e.Texto) like '%SUELY ALVES DE ARAUJO%' OR 
UPPER(e.Texto) like '%MARQUILEUDO DE LIMA PERES%' OR 
UPPER(e.Texto) like '%JOSE DE OLIVEIRA MAIA%' OR 
UPPER(e.Texto) like '%MARGARIDA DA SILVA LIMA%' OR 
UPPER(e.Texto) like '%ANTONIA ANDRADE DE ARAUJO%' OR 
UPPER(e.Texto) like '%MARIA JULIA NUNES DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA RAIMUNDA DE SOUZA FERREIRA%' OR 
UPPER(e.Texto) like '%RAIMUNDO RODRIGUES DE SOUZA%' OR 
UPPER(e.Texto) like '%MARIA DE LOURDES DO NASCIMENTO ABREU%' OR 
UPPER(e.Texto) like '%VALDIR FERREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%SEBASTIAO GOMES DINIS%' OR 
UPPER(e.Texto) like '%ODINEIDE SOARES DA SILVA%' OR 
UPPER(e.Texto) like '%SUEMILDO PINTO MOURAO%' OR 
UPPER(e.Texto) like '%MANOEL RUFINO DE LIMA%' OR 
UPPER(e.Texto) like '%FRANCISCO ASSIS MELO DA COSTA%' OR 
UPPER(e.Texto) like '%ELIZANGELA PAULA DA SILVA%' OR 
UPPER(e.Texto) like '%ANTONIA DEYSE SEVERIANO CAMPOS%' OR 
UPPER(e.Texto) like '%RODOLFO BADER NETO%' OR 
UPPER(e.Texto) like '%SILVIO ROBERTO ZUZA DA COSTA%' OR 
UPPER(e.Texto) like '%FRANCISCA EVILENE ARAUJO MACHADO%' OR 
UPPER(e.Texto) like '%MARIA DE JESUS DE OLIVEIRA RIOS%' OR 
UPPER(e.Texto) like '%GILSON LIMA DE CARVALHO%' OR 
UPPER(e.Texto) like '%JOSEMARY CASSIANO DOS SANTOS%' OR 
UPPER(e.Texto) like '%ALCIDES VALOIS DE MELO%' OR 
UPPER(e.Texto) like '%RAIMUNDA NONATA ESTEVAO DOS SANTOS SILVA%' OR 
UPPER(e.Texto) like '%JUCELIA BRAZILINA DA CRUZ%' OR 
UPPER(e.Texto) like '%MARIA ANTONIA MESQUITA DE SOUZA%' OR 
UPPER(e.Texto) like '%MARIA DE SOUZA MACIEL%' OR 
UPPER(e.Texto) like '%EUDILINA FERREIRA GOMES%' OR 
UPPER(e.Texto) like '%EUDILINA FERREIRA GOMES%' OR 
UPPER(e.Texto) like '%FLAVIANO CARUTA QUINTELA%' OR 
UPPER(e.Texto) like '%FLAVIANO CARUTA QUINTELA%' OR 
UPPER(e.Texto) like '%GILBERTO ALVES DE MEDEIROS%' OR 
UPPER(e.Texto) like '%IVANILDE BERNARDINO DE LIMA%' OR 
UPPER(e.Texto) like '%MARIA BENEDITA DA SILVA%' OR 
UPPER(e.Texto) like '%RAIMUNDO NONATO MOTA MEDIM%' OR 
UPPER(e.Texto) like '%ELISANGELA JUCA DE MIRANDA%' OR 
UPPER(e.Texto) like '%OLINDA MOREIRA LOPES%' OR 
UPPER(e.Texto) like '%OLINDA MOREIRA LOPES%' OR 
UPPER(e.Texto) like '%MARIA ANTONIA SILVA DOS SANTOS%' OR 
UPPER(e.Texto) like '%ANA BARBOSA CAMPOS%' OR 
UPPER(e.Texto) like '%EDIVAL DE LIMA RIOS%' OR 
UPPER(e.Texto) like '%EDIVAL DE LIMA RIOS%' OR 
UPPER(e.Texto) like '%ROSANGELA MACIEL DE MEDEIROS%' OR 
UPPER(e.Texto) like '%MARIA ROSANGELA COELHO FERRAZ%' OR 
UPPER(e.Texto) like '%RAIMUNDA BATISTA DE FREITAS%' OR 
UPPER(e.Texto) like '%MARIA PERPETUA DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA PERPETUA DA SILVA%' OR 
UPPER(e.Texto) like '%MARCOS ANTONIO DA SILVA CARVALHO%' OR 
UPPER(e.Texto) like '%JOAO LUIZ DE SOUZA%' OR 
UPPER(e.Texto) like '%MARIA SUELI GUIMARAES SOARES%' OR 
UPPER(e.Texto) like '%MARINA DOS SANTOS CAMPOS%' OR 
UPPER(e.Texto) like '%RAIMUNDA BATISTA LOPES%' OR 
UPPER(e.Texto) like '%ANTONIO SALLES%' OR 
UPPER(e.Texto) like '%GILVANIO FERREIRA CORREA%' OR 
UPPER(e.Texto) like '%GILVANIO FERREIRA CORREA%' OR 
UPPER(e.Texto) like '%JUCILENE MENDES DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA ELIZA GADELHA%' OR 
UPPER(e.Texto) like '%ALEXANDRE MARQUES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%MARILEUSA FONSECA DE SOUZA%' OR 
UPPER(e.Texto) like '%JOSE AUGUSTO FERREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%ALDENIZA VASCONCELOS DA SILVA%' OR 
UPPER(e.Texto) like '%SHIRLENE SOUSA LESSA%' OR 
UPPER(e.Texto) like '%SANDRA OSEIAS ALVES FRAGA JIMENEZ%' OR 
UPPER(e.Texto) like '%MARIA GIRLANDA LIMA DA ROCHA%' OR 
UPPER(e.Texto) like '%VILMACY DE BARROS RODRIGUES%' OR 
UPPER(e.Texto) like '%FRANCISCO PEREIRA DE FREITAS%' OR 
UPPER(e.Texto) like '%FRANCISCO PEREIRA DE FREITAS%' OR 
UPPER(e.Texto) like '%LUCIMAR CABRAL DE SOUZA%' OR 
UPPER(e.Texto) like '%LUCIMAR CABRAL DE SOUZA%' OR 
UPPER(e.Texto) like '%TANIA REGINA PEREIRA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%LUZINEIDE DA SILVA NASCIMENTO%' OR 
UPPER(e.Texto) like '%OSVALDO ARAUJO DE CASTRO%' OR 
UPPER(e.Texto) like '%ANTONIA COSTA DE ABREU%' OR 
UPPER(e.Texto) like '%ANTONIO VIANA DE ALMEIDA%' OR 
UPPER(e.Texto) like '%ANTONIO VIANA DE ALMEIDA%' OR 
UPPER(e.Texto) like '%ELIVALDO DA SILVA PEREIRA%' OR 
UPPER(e.Texto) like '%NONATO GOMES DE SOUZA%' OR 
UPPER(e.Texto) like '%ROSEMIR PAIVA DE SOUZA%' OR 
UPPER(e.Texto) like '%SEBASTIAO NOGUEIRA DA ROCHA%' OR 
UPPER(e.Texto) like '%ELIZABETH SABINO DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%RAIMUNDO NONATO FERREIRA TOJAL%' OR 
UPPER(e.Texto) like '%SILVANIA NERY VIANA%' OR 
UPPER(e.Texto) like '%RAIMUNDA NASCIMENTO DOS SANTOS%' OR 
UPPER(e.Texto) like '%CARLOS ALBERTOS DAS NEVES HENRIQUE%' OR 
UPPER(e.Texto) like '%MACMAILLAN DA COSTA DINIZ%' OR 
UPPER(e.Texto) like '%ALCIDES BENTO DE AZEVEDO%' OR 
UPPER(e.Texto) like '%MARINEZ DA SILVA ARAUJO DOS SANTOS%' OR 
UPPER(e.Texto) like '%IZAIAS FERREIRA LIMA%' OR 
UPPER(e.Texto) like '%MARIA DO SOCORRO DO NASCIMENTO SOUZA%' OR 
UPPER(e.Texto) like '%COSMA SILVA DE SOUZA%' OR 
UPPER(e.Texto) like '%MARIA DE JESUS MENDONCA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%MILTON MACEDO MONTES%' OR 
UPPER(e.Texto) like '%MILTON MACEDO MONTES%' OR 
UPPER(e.Texto) like '%VALDECIR PRUDENCIO MOTA%' OR 
UPPER(e.Texto) like '%MARIA ALAIZA DE LIMA MARQUES%' OR 
UPPER(e.Texto) like '%MARCOS GLAY RIBEIRO DE SOUZA%' OR 
UPPER(e.Texto) like '%JUDSON SILVA COSTA%' OR 
UPPER(e.Texto) like '%JUDSON SILVA COSTA%' OR 
UPPER(e.Texto) like '%MARIA BATISTA RUFINO%' OR 
UPPER(e.Texto) like '%LUIZ MARIA DA SILVA ALMEIDA%' OR 
UPPER(e.Texto) like '%CLEIDER DA SILVA SANTOS%' OR 
UPPER(e.Texto) like '%MARIA ANGELA DE OLIVEIRA LIMA%' OR 
UPPER(e.Texto) like '%JORGE LEANDRO DE SOUZA%' OR 
UPPER(e.Texto) like '%ANTONIO PINTO BEZERRA%' OR 
UPPER(e.Texto) like '%ORLANDINA DAMASCENO GOIS%' OR 
UPPER(e.Texto) like '%LUIZ MARIA DA SILVA ALMEIDA%' OR 
UPPER(e.Texto) like '%JOSE RUFINO DA SILVA%' OR 
UPPER(e.Texto) like '%RODRIGO JOSE DE SANTANA%' OR 
UPPER(e.Texto) like '%DALILA DE LIMA PERES%' OR 
UPPER(e.Texto) like '%ADAIL DANTAS DE SOUZA%' OR 
UPPER(e.Texto) like '%JOAO VIEIRA DOS SANTOS%' OR 
UPPER(e.Texto) like '%JOEL RUFINO MOTA%' OR 
UPPER(e.Texto) like '%LUCIRENE BARBOSA DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%GENEZIO MARQUES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%FRANCISCO FERREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%CICERO FEITOSA DOS SANTOS%' OR 
UPPER(e.Texto) like '%CLIVIA VICTOR DA SILVA%' OR 
UPPER(e.Texto) like '%BEATRIZ DE SOUZA LIMA%' OR 
UPPER(e.Texto) like '%FRANCILENE NUNES PEREIRA%' OR 
UPPER(e.Texto) like '%ETEVALDO SARMENTO FORMIGA%' OR 
UPPER(e.Texto) like '%ROBSON MENDONCA DANTAS%' OR 
UPPER(e.Texto) like '%MARIA LUCI VIANA FONTINELE%' OR 
UPPER(e.Texto) like '%ENEYDA SEGOBIA FURTADO%' OR 
UPPER(e.Texto) like '%MANOEL FILGUEIRAS%' OR 
UPPER(e.Texto) like '%RAIMUNDO JUCELINO TAVARES CAMPOS%' OR 
UPPER(e.Texto) like '%ALDEIR MACHADO DE MENDONCA JUNIOR%' OR 
UPPER(e.Texto) like '%SIMONE JAQUES DE AZAMBUJA SANTIAGO%' OR 
UPPER(e.Texto) like '%ROBSON CLAUDIO DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA IZABEL PINHEIRO DE ARAUJO%' OR 
UPPER(e.Texto) like '%OSVALDO RODRIGUES%' OR 
UPPER(e.Texto) like '%RAIMUNDO OLIVEIRA DA CRUZ%' OR 
UPPER(e.Texto) like '%ZULEIDE DE OLIVEIRA MAIA%' OR 
UPPER(e.Texto) like '%MARTA MARIA VITTORAZZI TESSINARI%' OR 
UPPER(e.Texto) like '%CARLOS SALES SOBRINHO%' OR 
UPPER(e.Texto) like '%REGIANE MACIEL DE MEDEIROS%' OR 
UPPER(e.Texto) like '%EDNILSON MAIA DE SOUZA%' OR 
UPPER(e.Texto) like '%JOSEVALDO MIRANDA DE CARVALHO%' OR 
UPPER(e.Texto) like '%MARIA LEIDINALVA DA SILVA LIMA%' OR 
UPPER(e.Texto) like '%IVONE DAMASCENO GOIS%' OR 
UPPER(e.Texto) like '%TEREZINHA DE MESQUITA RIBEIRO%' OR 
UPPER(e.Texto) like '%MARIA FRANCISCA OLIVEIRA DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA DE NAZARE PEREIRA LIMA DE CARVALHO%' OR 
UPPER(e.Texto) like '%RAIMUNDO RODRIGUES DE ANDRADE%' OR 
UPPER(e.Texto) like '%SARITA SOARES DE SOUZA%' OR 
UPPER(e.Texto) like '%EUDINEIA FERREIRA GOMES%' OR 
UPPER(e.Texto) like '%ENIR ALCANTARA CUNHA%' OR 
UPPER(e.Texto) like '%NATALIA DE OLIVEIRA BRAGA%' OR 
UPPER(e.Texto) like '%RYSTER FREIRE RODRIGUES%' OR 
UPPER(e.Texto) like '%VALDOMIRO BARBOSA DE SOUSA%' OR 
UPPER(e.Texto) like '%RAQUEL DA SILVA BRAGA%' OR 
UPPER(e.Texto) like '%OSMILDE SOUZA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%RAIMUNDA COSTA DA SILVA%' OR 
UPPER(e.Texto) like '%SAMUEL OLIVEIRA GOMES%' OR 
UPPER(e.Texto) like '%LINDALVA DOS SANTOS PEREIRA%' OR 
UPPER(e.Texto) like '%FRANCISCO IRINEUDO BARROS DE MESQUITA%' OR 
UPPER(e.Texto) like '%ARLINDO FERREIRA DA CUNHA JUNIOR%' OR 
UPPER(e.Texto) like '%JUCIVANIA PINHEIRO DE NEGREIROS%' OR 
UPPER(e.Texto) like '%EDMILSON MARTINS DA SILVA%' OR 
UPPER(e.Texto) like '%FRANCISCO ANTONIO SOARES DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%ROBERTO ALVES DE MELO%' OR 
UPPER(e.Texto) like '%JOSE BARBOSA DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%ALEX FABIANNE VIANA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%ANTONIO CARLOS SOUZA DA SILVA%' OR 
UPPER(e.Texto) like '%ANTONIO CARLOS SOUZA DA SILVA%' OR 
UPPER(e.Texto) like '%CREUZA RAMOS DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA DO SOCORRO MARQUES FREIRE%' OR 
UPPER(e.Texto) like '%MARIA DO SOCORRO DE OLIVEIRA FONTINELE%' OR 
UPPER(e.Texto) like '%MARIA DA CONCEICAO ESTEVES BEZERRA%' OR 
UPPER(e.Texto) like '%JAMIL FERREIRA BRASIL%' OR 
UPPER(e.Texto) like '%FRANCISCO SEVERIANO DE SOUZA%' OR 
UPPER(e.Texto) like '%FRANCISCO EUDES DE SOUZA%' OR 
UPPER(e.Texto) like '%RAIMUNDO PEREIRA DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%MARIA SALETE DA SILVA%' OR 
UPPER(e.Texto) like '%DEBORA DA ROCHA SILVA%' OR 
UPPER(e.Texto) like '%LUIZ GONZAGA DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%RAIMUNDA BRANDO DA SILVA%' OR 
UPPER(e.Texto) like '%VENUZA MESQUITA DE SOUZA%' OR 
UPPER(e.Texto) like '%RAIMUNDO CARLOS PEIXOTO DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA GENY ASSUNCAO DA CONCEICAO%' OR 
UPPER(e.Texto) like '%JANETE DE CASTRO FIGUEIREDO%' OR 
UPPER(e.Texto) like '%MARIA MARTINS DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA MARTINS DA SILVA%' OR 
UPPER(e.Texto) like '%SEVERINO AGOSTINHO PONTES FILHO%' OR 
UPPER(e.Texto) like '%SEVERINO AGOSTINHO PONTES FILHO%' OR 
UPPER(e.Texto) like '%ELIZABETE SOUZA DE ALMEIDA%' OR 
UPPER(e.Texto) like '%MARIA AUXILIADORA PEREIRA DE SANTANA%' OR 
UPPER(e.Texto) like '%MARIA BARBOSA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%MARIA BARBOSA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%JUCELI PEREIRA GUERRA%' OR 
UPPER(e.Texto) like '%JULIA CARVALHO DE LIMA%' OR 
UPPER(e.Texto) like '%MANOEL QUEIROZ DA SILVA%' OR 
UPPER(e.Texto) like '%FRANCISCO FATIMO SILVA DE CARVALHO%' OR 
UPPER(e.Texto) like '%FRANCISCO FATIMO SILVA DE CARVALHO%' OR 
UPPER(e.Texto) like '%RITA NONATA DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA IVONETE BRAGA DE PAULA%' OR 
UPPER(e.Texto) like '%VERA LUCIA OLIVEIRA DA CUNHA%' OR 
UPPER(e.Texto) like '%MARLY FLORA BRAGA DA SILVA%' OR 
UPPER(e.Texto) like '%CHARLES DE ALCANTARA OLIVEIRA%' OR 
UPPER(e.Texto) like '%ELOIZO DA SILVA SOARES%' OR 
UPPER(e.Texto) like '%JORGE PEREIRA DE ARAUJO%' OR 
UPPER(e.Texto) like '%RONDOLFO BARRETO%' OR 
UPPER(e.Texto) like '%FRANCISCA SILVA DA COSTA%' OR 
UPPER(e.Texto) like '%VOMEA MARIA DE ARAUJO%' OR 
UPPER(e.Texto) like '%RAIMUNDO CARNEIRO DE FARIAS%' OR 
UPPER(e.Texto) like '%ELIANE MAIA DE ARAUJO%' OR 
UPPER(e.Texto) like '%JORGE FERNANDES DE LIMA%' OR 
UPPER(e.Texto) like '%MARIA TELES DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%FLORIDA MACHADO%' OR 
UPPER(e.Texto) like '%JOCIANA DOS SANTOS DA SILVA%' OR 
UPPER(e.Texto) like '%EDILBERTO PEREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%RITA AMELIA TORRES DOS SANTOS%' OR 
UPPER(e.Texto) like '%VANIA ALVES DOS SANTOS%' OR 
UPPER(e.Texto) like '%MARCOS AURELIO BRANDO DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA SUELI RODRIGUES DOS SANTOS%' OR 
UPPER(e.Texto) like '%JAIR AZEVEDO AIRES%' OR 
UPPER(e.Texto) like '%RAIMUNDO PEREIRA NUNES%' OR 
UPPER(e.Texto) like '%PAULO CESAR SOARES RIOS%' OR 
UPPER(e.Texto) like '%MARIA JOSE DOS SANTOS%' OR 
UPPER(e.Texto) like '%MANOEL RUI PERES%' OR 
UPPER(e.Texto) like '%VICENTE RODRIGUES BARBOSA NETO%' OR 
UPPER(e.Texto) like '%VICENTE RODRIGUES BARBOSA NETO%' OR 
UPPER(e.Texto) like '%ANTONIA ALDENICE SANTOS DA SILVA%' OR 
UPPER(e.Texto) like '%CARLOS AUGUSTO SILVA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%ODAIR JOSE SOARES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%RAIMUNDO PEREIRA DE FREITAS%' OR 
UPPER(e.Texto) like '%ROGERIO BARCELLOS FERRAZ%' OR 
UPPER(e.Texto) like '%MILENA GONCALVES SALES%' OR 
UPPER(e.Texto) like '%CLAUDIONORA DILENIR DE PAIVA%' OR 
UPPER(e.Texto) like '%SEBASTIAO ESMERINDO DE SOUZA DA SILVA%' OR 
UPPER(e.Texto) like '%RAIMUNDA ALVES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%FRANCISCO ALVES DO NASCIMENTO FILHO%' OR 
UPPER(e.Texto) like '%JULIANA FERREIRA DE LIRA%' OR 
UPPER(e.Texto) like '%MARCIO ANTONIO SOARES DE LIMA%' OR 
UPPER(e.Texto) like '%MANOEL MARTINS DE LIMA%' OR 
UPPER(e.Texto) like '%EUDO LUSTOSA BRASIL%' OR 
UPPER(e.Texto) like '%JOSE SANTOS DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%ANTONIO JOSE RODRIGUES MARCOS%' OR 
UPPER(e.Texto) like '%MANOEL MOREIRA DE ARAUJO%' OR 
UPPER(e.Texto) like '%FRANCISCO FERREIRA DE ARAUJO%' OR 
UPPER(e.Texto) like '%NEUTON ALVES DE LIMA%' OR 
UPPER(e.Texto) like '%ELIONELDO RUI PERES%' OR 
UPPER(e.Texto) like '%MARIA DA SILVA FILGUEIRA%' OR 
UPPER(e.Texto) like '%HELENILDA DO NASCIMENTO RODRIGUES%' OR 
UPPER(e.Texto) like '%RAIMUNDO ROBERTO CAMARA GOMES%' OR 
UPPER(e.Texto) like '%RAIMUNDO ROBERTO CAMARA GOMES%' OR 
UPPER(e.Texto) like '%WILSON DOS SANTOS MORAIS%' OR 
UPPER(e.Texto) like '%MARIA DA CONCEICAO BENIGNO DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA DA CONCEICAO BENIGNO DA SILVA%' OR 
UPPER(e.Texto) like '%ODIRLEI MOREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%AURILENE BARBOSA FARIAS%' OR 
UPPER(e.Texto) like '%AURILENE BARBOSA FARIAS%' OR 
UPPER(e.Texto) like '%EDILBERTO DA SILVA LIRA%' OR 
UPPER(e.Texto) like '%MARILEUDA CARDOSO DOS SANTOS%' OR 
UPPER(e.Texto) like '%ELZA BARBOSA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%REDINEI SILVA MATOS%' OR 
UPPER(e.Texto) like '%IRACEMA FERREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%ZULEIDE DA SILVA MIGUEL%' OR 
UPPER(e.Texto) like '%IVONE FILGUEIRA DA SILVA%' OR 
UPPER(e.Texto) like '%RICARDO OTAVIO DE SOUZA%' OR 
UPPER(e.Texto) like '%NEIVA APARECIDA BADOTTI MARQUES%' OR 
UPPER(e.Texto) like '%FRANCISCO DAS CHAGAS SOARES GADELHA%' OR 
UPPER(e.Texto) like '%MARIA DO SOCORRO ANSELMO DE SOUZA SILVA%' OR 
UPPER(e.Texto) like '%MANOEL ALVES DA COSTA%' OR 
UPPER(e.Texto) like '%RONED DE OLIVEIRA SILVA%' OR 
UPPER(e.Texto) like '%MARIOLINO RODRIGUES%' OR 
UPPER(e.Texto) like '%MARIA DO ROSARIO FELIX DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%FRANCISCA REGO DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%FRANCISCO DAS CHAGAS ALENCAR DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%EDIMAR FREIRES PONTES%' OR 
UPPER(e.Texto) like '%HILDA PEREIRA DE LIMA%' OR 
UPPER(e.Texto) like '%GERCILENE DA SILVA SOUZA%' OR 
UPPER(e.Texto) like '%JOSE NOGUEIRA COSTA%' OR 
UPPER(e.Texto) like '%EVALDO BEZERRA DA SILVA%' OR 
UPPER(e.Texto) like '%MANOEL ZACARIAS DE LIMA%' OR 
UPPER(e.Texto) like '%MANOEL DO CARMO SILVA%' OR 
UPPER(e.Texto) like '%MARGARIDA COELHO FERNANDES EVANGELISTA%' OR 
UPPER(e.Texto) like '%MARIA CASTORINA RODRIGUES%' OR 
UPPER(e.Texto) like '%ANTONIO JOSE VIERA DINIZ%' OR 
UPPER(e.Texto) like '%MARIA MADALENA FEITOSA%' OR 
UPPER(e.Texto) like '%RAIMUNDO FERREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%LEILA MARIA DINIZ GOUVEIA%' OR 
UPPER(e.Texto) like '%DELSIMAR FERREIRA DOS SANTOS%' OR 
UPPER(e.Texto) like '%SEBASTIÃO CARLOS DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%RAIMUNDO COELHO DOS SANTOS%' OR 
UPPER(e.Texto) like '%DENIS AUGUSTO KAXINAWA%' OR 
UPPER(e.Texto) like '%MARIA DO SOCORRO MACIEL DE SOUZA%' OR 
UPPER(e.Texto) like '%SEBASTIAO MIGUEL DE BRITO%' OR 
UPPER(e.Texto) like '%ANTONIO JOSE LUZ DA SILVA%' OR 
UPPER(e.Texto) like '%ERCILIA BATISTA DE AMORIM%' OR 
UPPER(e.Texto) like '%JOSE GUILHERME DE ALMEIDA ALBUQUERQUE%' OR 
UPPER(e.Texto) like '%VICTOR COELHO DA SILVA%' OR 
UPPER(e.Texto) like '%ANTONIO DA SILVA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%RAIMUNDO NONATO DA SILVA%' OR 
UPPER(e.Texto) like '%FRANCISCO ADRIANO FRANKLIN FEITOSA%' OR 
UPPER(e.Texto) like '%JOSERLY DE SOUZA LIMA NASCIMENTO%' OR 
UPPER(e.Texto) like '%DAVI LOPES SORIA%' OR 
UPPER(e.Texto) like '%ANTONIO OLIVEIRA DA SILVA%' OR 
UPPER(e.Texto) like '%RAIMUNDO DA SILVA REGO%' OR 
UPPER(e.Texto) like '%ALBANIZA DA SILVA%' OR 
UPPER(e.Texto) like '%GLAUCIO SARAIVA DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA SILVA DE CASTRO%' OR 
UPPER(e.Texto) like '%ELVES MATEUS CASTRO DE MELO%' OR 
UPPER(e.Texto) like '%ALDEMIR MACIEL COSTA%' OR 
UPPER(e.Texto) like '%VALDERI FERREIRA NERES%' OR 
UPPER(e.Texto) like '%JOSE LIMA DA COSTA%' OR 
UPPER(e.Texto) like '%SEBASTIAO PEREIRA SOBRINHO%' OR 
UPPER(e.Texto) like '%MARIA JOSE CORDEIRO DA SILVA%' OR 
UPPER(e.Texto) like '%RILDO COSTA DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%SILVANA RAMOS DE LIMA%' OR 
UPPER(e.Texto) like '%TEREZINHA BATISTA DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%RAIMUNDO FREITAS DA SILVA%' OR 
UPPER(e.Texto) like '%FRANCISCA BATISTA DE NAZARE%' OR 
UPPER(e.Texto) like '%MARCOS ANTONIO DO NASCIMENTO ARAUJO%' OR 
UPPER(e.Texto) like '%FRANCISCO DE ASSIS LEITE TELES%' OR 
UPPER(e.Texto) like '%MARIA FRANCISCA BRILHANTE%' OR 
UPPER(e.Texto) like '%CLOVIS AZEVEDO NEGREIROS%' OR 
UPPER(e.Texto) like '%MARIA PEREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%RAIMUNDO FRANCISCO ADRIÃO%' OR 
UPPER(e.Texto) like '%MARIA DA PENHA BENFICA%' OR 
UPPER(e.Texto) like '%COSME HONORATO DA SILVA%' OR 
UPPER(e.Texto) like '%JOSE FILIZARDO DA SILVA%' OR 
UPPER(e.Texto) like '%SEBASTIANA SAMPAIO%' OR 
UPPER(e.Texto) like '%IVENIO MOREIRA DE SOUZA%' OR 
UPPER(e.Texto) like '%VALDOMIRO OLIVEIRA DE SOUZA%' OR 
UPPER(e.Texto) like '%MANOEL LACERDA ARAUJO DA SILVA%' OR 
UPPER(e.Texto) like '%ANTONIO JORGE DOS SANTOS CARVALHO%' OR 
UPPER(e.Texto) like '%JOAO RODRIGUES DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%SILVIO SIQUEIRA LIMA%' OR 
UPPER(e.Texto) like '%ANTONIO RAIMUNDO DAS CHAGAS%' OR 
UPPER(e.Texto) like '%VALDEMAR RIBEIRO DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%NABOR NOGUEIRA JUSTINO%' OR 
UPPER(e.Texto) like '%FRANCISCA ACACIA DE ALENCAR%' OR 
UPPER(e.Texto) like '%JOSE LOPES MATEUS%' OR 
UPPER(e.Texto) like '%MARILZA MOREIRA DA SILVA%' OR 
UPPER(e.Texto) like '%JOSE CLEOMAR GOMES DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%MARIA DO SOCORRO CANDIDO DE MIRANDA%' OR 
UPPER(e.Texto) like '%MARIA LIZETE DO NASCIMENTO LOPES%' OR 
UPPER(e.Texto) like '%CLAY CLEMENTE%' OR 
UPPER(e.Texto) like '%IDELCY PEREIRA FILHO%' OR 
UPPER(e.Texto) like '%ALCINA FEITOSA DA SILVA%' OR 
UPPER(e.Texto) like '%VALDERI DIAS BOA%' OR 
UPPER(e.Texto) like '%ISABEL ALTINA DE MORAIS%' OR 
UPPER(e.Texto) like '%ANA CLAUDIA JUCA DE MIRANDA%' OR 
UPPER(e.Texto) like '%ADENILSON DE LIMA CANDIDO%' OR 
UPPER(e.Texto) like '%JOSEMILDO DE SOUZA AZEVEDO%' OR 
UPPER(e.Texto) like '%GERMANISIO FURTADO DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%SANDRO ROGÉRIO TORRES PESSOA%' OR 
UPPER(e.Texto) like '%MARIA LUCILIA DE SOUZA IBIAPINA%' OR 
UPPER(e.Texto) like '%VALMY DARC DO NASCIMENTO%' OR 
UPPER(e.Texto) like '%JOSEDATE VALDEZ DE ARAUJO%' OR 
UPPER(e.Texto) like '%FRANCISCA BEZERRA FEITOZA%' OR 
UPPER(e.Texto) like '%ALMI RODRIGUES DA SILVA%' OR 
UPPER(e.Texto) like '%RAULDEMIR SILVEIRA%' OR 
UPPER(e.Texto) like '%VIRGINIA OLIVEIRA VIVEIROS%' OR 
UPPER(e.Texto) like '%PEDRO HENRIQUE DE OLIVEIRA VIVEIROS%' OR 
UPPER(e.Texto) like '%ECINAIRO DA SILVA CARVALHO%' OR 
UPPER(e.Texto) like '%ZINDOMAR ZENON DE SOUZA GALDINO%' OR 
UPPER(e.Texto) like '%FRANCISCA AUZENILDA OLIVEIRA DA SILVA%' OR 
UPPER(e.Texto) like '%IZAQUIELE VALDEZ DE ARAUJO%' OR 
UPPER(e.Texto) like '%FRANÇA PINHEIROS DOMINGOS KAXINAWA%' OR 
UPPER(e.Texto) like '%RENAN MENDES SOARES%' OR 
UPPER(e.Texto) like '%ANTONIO JOSE SANTOS DE SOUZA%' OR 
UPPER(e.Texto) like '%CIDIA FARIAS DE MENDONÇA%' OR 
UPPER(e.Texto) like '%MANUEL JUSTINO DA SILVA LOPES%' OR 
UPPER(e.Texto) like '%ANGELA MARIA SILVA DE ALMEIDA FARIAS%' OR 
UPPER(e.Texto) like '%FERNANDO ALVES%' OR 
UPPER(e.Texto) like '%LUCIANO MEIRA PRAIS%' OR 
UPPER(e.Texto) like '%JOSE APARECIDO VIEIRA DE MENDONÇA%' OR 
UPPER(e.Texto) like '%JOSE OSMAR DE SOUSA%' OR 
UPPER(e.Texto) like '%EMILSON NEGREIRO DE ALMEIDA%' OR 
UPPER(e.Texto) like '%JOSE CARLOS DE MORAES%' OR 
UPPER(e.Texto) like '%ROSA PEREZ KAXINAWÁ%' OR 
UPPER(e.Texto) like '%MARIA APARECIDA BENFICA%' OR 
UPPER(e.Texto) like '%MARIA DA CONCEIÇÃO FIRME NORUEGA%' OR 
UPPER(e.Texto) like '%ROSELI FRANCO DA SILVA%' OR 
UPPER(e.Texto) like '%VANUZIA COSTA DA SILVA MOREIRA%' OR 
UPPER(e.Texto) like '%EDNON MOREIRA SOARES%' OR 
UPPER(e.Texto) like '%JOSE CARLOS INACIO DE ABREU%' OR 
UPPER(e.Texto) like '%RAIMUNDO ROBERTO CAMARA GOMES%' OR 
UPPER(e.Texto) like '%DAUTO DE ARAUJO MARTINS%' OR 
UPPER(e.Texto) like '%PEDRO MOISES KAXINAWÁ%' OR 
UPPER(e.Texto) like '%SILDO FERNANDES PERET%' OR 
UPPER(e.Texto) like '%DEUSIMAR PIMENTA DE FREITAS%' OR 
UPPER(e.Texto) like '%LIDIANE DINIZ GOUVEIA%' OR 
UPPER(e.Texto) like '%PEDRO TENE DOMINGOS SALOMÃO HUNIKUI%' OR 
UPPER(e.Texto) like '%ANTONIO JOSE DA SILVA FERREIRA%' OR 
UPPER(e.Texto) like '%OZINALDO NASCIMENTO DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%RENE ALVES DA COSTA%' OR 
UPPER(e.Texto) like '%MARIA GRACIETE DA SILVA ARAUJO%' OR 
UPPER(e.Texto) like '%DANIEL DE ARAUJO MARTINS%' OR 
UPPER(e.Texto) like '%ANTONIO VEGEAN LIMA DINIZ%' OR 
UPPER(e.Texto) like '%ROSIMEYRE FEITOZA DOS SANTOS%' OR 
UPPER(e.Texto) like '%ANTONIA DA SILVA GOMES%' OR 
UPPER(e.Texto) like '%JHAIMME ADRIANN RODRIGUES DA SILVA%' OR 
UPPER(e.Texto) like '%ANTONIO VITOR DAMASCENO%' OR 
UPPER(e.Texto) like '%MARISETE DE LIMA%' OR 
UPPER(e.Texto) like '%ANTONIO LIMA DA SILVA%' OR 
UPPER(e.Texto) like '%MANOEL RODRIGUES DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%EUNICE GOMES DA SILVA%' OR 
UPPER(e.Texto) like '%ARLIANE LIMA DE HOLANDA%' OR 
UPPER(e.Texto) like '%FRANCISCO JOZICLE SANTIAGO SIQUEIRA%' OR 
UPPER(e.Texto) like '%RAIMUNDO FERREIRA DE SOUZA PEREIRA%' OR 
UPPER(e.Texto) like '%WILKEN ANTONIO PEREZ BRAGA%' OR 
UPPER(e.Texto) like '%EDVALDO MIRANDA DINIZ%' OR 
UPPER(e.Texto) like '%MARINEUDO SILVA E SILVA%' OR 
UPPER(e.Texto) like '%SANDRO LUIZ GOMES BRAGA%' OR 
UPPER(e.Texto) like '%DEUZIMAR ALVES DE ALBUQUERQUE%' OR 
UPPER(e.Texto) like '%FRANCISCO LOPES AUGUSTO KAXINAWÁ%' OR 
UPPER(e.Texto) like '%AZENCLEVER RODRIGUES CORREA%' OR 
UPPER(e.Texto) like '%FABIO CARDOSO DE SOUZA%' OR 
UPPER(e.Texto) like '%EMERSON BEZERRA DA ROCHA%' OR 
UPPER(e.Texto) like '%FRANCISCO JEAN SALDANHA FIGUEREDO%' OR 
UPPER(e.Texto) like '%ANTONIA LUCELIA ARAUJO SOUZA%' OR 
UPPER(e.Texto) like '%MARCOS GLAY RIBEIRO DE SOUZA%' OR 
UPPER(e.Texto) like '%FRANCISCA GLORIA DE QUEIROZ%' OR 
UPPER(e.Texto) like '%ITAMAR LOPES SAMPAIO KAXINAWÁ%' OR 
UPPER(e.Texto) like '%MARIA DE NAZARE MARQUES DA SILVA%' OR 
UPPER(e.Texto) like '%JOSE DE OLIVEIRA%' OR 
UPPER(e.Texto) like '%QUEILA LOPES FERREIRA%' OR 
UPPER(e.Texto) like '%DAIANE TEIXEIRA FERREIRA%' OR 
UPPER(e.Texto) like '%ECIMAIRO DA SILVA CARVALHO%' OR 
UPPER(e.Texto) like '%SAMUEL GOMES DA COSTA%' OR 
UPPER(e.Texto) like '%CELIA PERES MATEUS KAXINAWA%' OR 
UPPER(e.Texto) like '%MARILEUDO SILVA E SILVA%' OR 
UPPER(e.Texto) like '%GILSON RABELO DA SILVA%' OR 
UPPER(e.Texto) like '%MARIA APARECIDA SILVA XAVIER%' OR 
UPPER(e.Texto) like '%ANTONIO TIAGO SILVA DE ARAUJO%' OR 
UPPER(e.Texto) like '%RONALD RODRIGUES DA SILVA%' OR 
UPPER(e.Texto) like '%EDINHO DE FREITAS JERONIMO%' OR 
UPPER(e.Texto) like '%JOSE FRANCISCO SILVA DA SILVEIRA%' OR 
UPPER(e.Texto) like '%DINIZ GUEDES DA SILVA%' OR 
UPPER(e.Texto) like '%NATALIA SOARES DE OLIVEIRA%'
